---
permalink: san-host/concept_ontap_target_releases_supported_by_7mtt.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, target, supported, 7, mode, tool 
summary: Die Release-Unterstützung für ONTAP Transition Ziel-Cluster hängt von der gewünschten Umstiegsmethode, dem Copy-Based oder Copy-Free und der Version des 7-Mode Transition Tools ab. 
---
= ONTAP Target Releases, die vom 7-Mode Transition Tool unterstützt werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Release-Unterstützung für ONTAP Transition Ziel-Cluster hängt von der gewünschten Umstiegsmethode, dem Copy-Based oder Copy-Free und der Version des 7-Mode Transition Tools ab.

In dem aktuellen 7-Mode Transition Tool _Release Notes_ finden Sie die neuesten Informationen zu unterstützten Zielversionen und bekannten Problemen.

https://docs.netapp.com/us-en/ontap-7mode-transition/releasenotes.html["Versionshinweise Für Das 7-Mode Transition Tool"]

Copy-Based Transitions werden für diese ONTAP Ziel-Releases unterstützt.

|===
| Wenn Ihr Übergangsziel läuft... | Sie müssen diese 7-Mode Transition Tool Version verwenden ... 


 a| 
ONTAP 9.7P2 oder höher 9.7 P Release


NOTE: Frühere Versionen von 9.7 werden nicht unterstützt.
 a| 
3.3.2



 a| 
ONTAP 9.6P7 oder höher 9.6 P Version


NOTE: Frühere Versionen von 9.6 werden nicht unterstützt.
 a| 
3.3.2



 a| 
ONTAP 9.5 oder eine frühere Version von ONTAP 9
 a| 
3.3.2 oder 3.3.1



 a| 
Clustered Data ONTAP 8.1.4P4 und neuere Versionen 8.x.
 a| 
3.3.2 oder 3.3.1

|===
Copy-Free Transitions werden zu diesen ONTAP Zielversionen mit dem 7-Mode Transition Tool 3.3 unterstützt.

* ONTAP 9.4 und frühere Versionen von ONTAP 9.
* Clustered Data ONTAP 8.3.2 und höher 8.x Versionen.



NOTE: Sie können das 7-Mode Transition Tool nicht mit der kopiefreien Methode auf ONTAP 9.5 oder höher umstellen. Hierfür müssen Sie zunächst zu ONTAP 9.4 mit dem 7-Mode Transition Tool 3.3.1 wechseln und dann Ihr Cluster auf ONTAP 9.5 oder höher aktualisieren. 7-Mode Transition Tool 3.3.2 unterstützt keine Copy-Free Transition.
