---
permalink: san-host/concept_vmware_esxi_host_remediation.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, esxi, host, remediation 
summary: 'Wenn Sie das 7-Mode Transition Tool \(7MTT\) für den Wechsel von Data ONTAP 7-Mode zu Clustered Data ONTAP in einer SAN-Umgebung verwenden, müssen Sie vor der Data ONTAP Transition eine Reihe von Schritten auf Ihren VMware ESXi Hosts durchführen. Sie müssen die Hosts vor der Umstellung herunterfahren und nach der Transition müssen Sie eine weitere Reihe von Schritten durchführen, bevor Sie mit der Datenspeicherung beginnen.' 
---
= Probleme mit dem VMware ESXi Host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie das 7-Mode Transition Tool (7MTT) für den Wechsel von Data ONTAP 7-Mode zu Clustered Data ONTAP in einer SAN-Umgebung verwenden, müssen Sie vor der Data ONTAP-Transition eine Reihe von Schritten auf Ihren VMware ESXi Hosts durchführen. Sie müssen die Hosts vor der Umstellung herunterfahren und nach der Transition müssen Sie eine weitere Reihe von Schritten durchführen, bevor Sie mit der Datenspeicherung beginnen.

*Verwandte Informationen*

xref:task_testing_transitioned_luns_and_esxi_host_applications_before_cutover.adoc[Die Tests übergegangen waren LUNs und ESXi Hostapplikationen vor der Umstellungsphase bei auf Kopien basierenden Übergängen]

xref:concept_post_transition_requirements_for_esxi_hosts.adoc[Anforderungen zur Behebung nach dem Umstieg für ESXi-Hosts]
