---
permalink: san-host/task_preparing_to_transition_solaris_host_data_luns_with_zfs_file_system.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, solaris, host, data, lun, zfs 
summary: Bevor Sie Solaris Host-LUNs mit ZFS-Dateisystemen von Data ONTAP im 7-Mode auf Clustered Data ONTAP umstellen, müssen Sie die für den Übergangsprozess erforderlichen Informationen erfassen. 
---
= Vorbereitung auf den Übergang von Solaris Host-Daten-LUNs mit ZFS-Dateisystem
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Solaris Host-LUNs mit ZFS-Dateisystemen von Data ONTAP im 7-Mode auf Clustered Data ONTAP umstellen, müssen Sie die für den Übergangsprozess erforderlichen Informationen erfassen.

Dies gilt für Copy-Based Transitions und Copy-Free Transitions.

.Schritte
. Geben Sie auf dem 7-Mode Controller den Namen der zu migrierte LUN an:
+
`*lun show*`

+
[listing]
----
 fas8040-shu01> lun show
        /vol/ufs/ufs1                  5g (5368709120)    (r/w, online, mapped)
        /vol/ufs/ufs2                  5g (5368709120)    (r/w, online, mapped)
        /vol/zfs/zfs1                  6g (6442450944)    (r/w, online, mapped)
        /vol/zfs/zfs2                  6g (6442450944)    (r/w, online, mapped)
----
. Suchen Sie auf dem Host den Dateinamen des SCSI-Geräts für die LUN:
+
`*sanlun lun show*`

+
Der Name der SCSI-Gerätedatei befindet sich im `device filename` Spalte.

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
fas8040-shu01        /vol/zfs/zfs2    /dev/rdsk/c0t60A98000383035356C2447384D396550d0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/zfs/zfs1    /dev/rdsk/c0t60A98000383035356C2447384D39654Ed0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/ufs/ufs2    /dev/rdsk/c0t60A98000383035356C2447384D39654Ad0s2 scsi_vhci0 FCP        5g      7
fas8040-shu01        /vol/ufs/ufs1    /dev/rdsk/c0t60A98000383035356C2447384D396548d0s2 scsi_vhci0 FCP        5g      7
----
. Zpool auflisten:
+
`*zpool list*`

. Notieren Sie das zpool und erhalten Sie die Laufwerke, die mit dem zpool verbunden sind:
+
`*zpool status _pool-name_*`

+
[listing]
----
# zpool list
NAME     SIZE  ALLOC   FREE  CAP  HEALTH  ALTROOT
n_pool  11.9G  2.67G  9.27G  22%  ONLINE  -

# zpool status
  pool: n_pool
 state: ONLINE
 scan: none requested
config:

        NAME                                     STATE     READ WRITE CKSUM
        n_pool                                   ONLINE       0     0     0
          c0t60A98000383035356C2447384D396550d0  ONLINE       0     0     0
          c0t60A98000383035356C2447384D39654Ed0  ONLINE       0     0     0

errors: No known data errors
----
. ZFS-Datensätze in einem ZFS-Speicherpool auflisten und aufzeichnen:
+
`*zfs list*`

+
[listing]
----
# zfs list
NAME           USED  AVAIL  REFER  MOUNTPOINT
n_pool        2.67G  9.08G   160K  /n_pool
n_pool/pool1  1.50G  2.50G  1.50G  /n_pool/pool1
n_pool/pool2  1.16G  2.84G  1.16G  /n_pool/pool2
----

