---
permalink: san-host/task_mounting_solaris_host_luns_with_sun_volume_manager_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, solaris, host, lun, volume, manager 
summary: Nach dem Übergang von Solaris Host LUNs mit Solaris Volume Manager von ONTAP im 7-Mode auf Clustered ONTAP müssen Sie die LUNs mounten. 
---
= Installieren von Solaris Host LUNs mit Solaris Volume Manager nach dem Umstieg
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Übergang von Solaris Host LUNs mit Solaris Volume Manager von ONTAP im 7-Mode auf Clustered ONTAP müssen Sie die LUNs mounten.

Bei Copy-Based Transitions führen Sie diese Schritte nach Abschluss des Storage-Umstellungsvorgangs im 7-Mode Transition Tool (7MTT) durch.

Bei Copy-Free Transitions führen Sie die folgenden Schritte aus, nachdem der Vorgang Daten und Konfiguration im 7MTT importiert wurde.

.Schritte
. Nutzen Sie die Neuerdeckung Ihrer neuen Clustered ONTAP LUNs durch erneutes Scannen des Hosts.
+
.. Identifizieren Sie die FC-Host-Ports (Typ fc-Fabric): +
`*#cfgadm _–l_*`
.. Heben Sie die Konfiguration des ersten fc-Fabric-Ports auf: +
`*#cfgadm –c unconfigure _c1_*`
.. Den zweiten fc-Fabric-Port: + aufheben
`*#cfgadm –c unconfigure _c2_*`
.. Wiederholen Sie die Schritte für andere fc-Fabric-Ports.
.. Überprüfen Sie die Host-Ports und die angeschlossenen Geräte: +
`*# cfgadm _–al_*`
.. Treiber neu laden: +
`*# devfsadm –Cv*`
+
`*# devfsadm –i iscsi*`



. Überprüfen Sie, ob die LUNs für Clustered ONTAP erkannt wurden:
+
`*sanlun lun show*`

+
** Der `lun-pathname` Die Werte für Clustered ONTAP LUNs sollten dieselben sein wie für `lun-pathname` Werte für die 7-Mode LUNs vor der Transition.
** Der `mode` Die Spalte sollte „`C`“ anstelle von „`7`“ anzeigen.


+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
vs_sru17_5           /vol/zfs/zfs2    /dev/rdsk/c5t600A0980383030444D2B466542485935d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/zfs/zfs1    /dev/rdsk/c5t600A0980383030444D2B466542485934d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/ufs/ufs2    /dev/rdsk/c5t600A0980383030444D2B466542485937d0s2 scsi_vhci0 FCP        5g      C
vs_sru17_5           /vol/ufs/ufs1    /dev/rdsk/c5t600A0980383030444D2B466542485936d0s2 scsi_vhci0 FCP        5g      C
----
. Importieren von Datenträgersätzen in vorhandene Solaris Volume Manager-Konfigurationen unter Verwendung desselben Festplatteneinsätzen:
+
`*metaimport -s _set-name_*`

+
[listing]
----
# metaimport -s svm
Drives in regular diskset including disk c0t60A98000383035356C2447384D39654Ad0:
  c0t60A98000383035356C2447384D39654Ad0
  c0t60A98000383035356C2447384D396548d0
More info:
  metaimport -r -v c0t60A98000383035356C2447384D39654Ad0

# metastat -s svm
svm/d2: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D396548d0s0          0     No      Yes

svm/d1: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D39654Ad0s0          0     No      Yes

Device Relocation Information:
Device                                           Reloc  Device ID
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes    id1,sd@n60a98000383035356c2447384d396548
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes    id1,sd@n60a98000383035356c2447384d39654a
----
. Dateisystemprüfung ausführen:
+
`*fsck -F ufs /dev/md/svm/rdsk/d1*`

+
[listing]
----
# fsck -F ufs /dev/md/svm/rdsk/d1
** /dev/md/svm/rdsk/d1
** Last Mounted on /d1
** Phase 1 - Check Blocks and Sizes
** Phase 2 - Check Pathnames
** Phase 3a - Check Connectivity
** Phase 3b - Verify Shadows/ACLs
** Phase 4 - Check Reference Counts
** Phase 5 - Check Cylinder Groups
3 files, 1573649 used, 3568109 free (13 frags, 446012 blocks, 0.0% fragmentation)
----
. Montieren Sie jedes Gerät manuell mit dem `mount` Befehl.
+
[listing]
----
# /sbin/mount -F ufs -o largefiles /dev/md/svm/dsk/d1  /d1
  # /sbin/mount -F ufs -o largefiles /dev/md/svm/dsk/d2  /d2
----
. Überprüfen Sie den Bereitstellungspunkt:
+
`*df -ah*`


