---
permalink: san-host/task_enabling_caw_on_a_datastore_using_esxi_cli.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, enable, caw, datastore, esxi, cli 
summary: 'Wenn Sie in Data ONTAP 7-Mode keine Unterstützung für „Compare and Write \(CAW\)“ hatten, müssen Sie beim Umstieg auf Clustered Data ONTAP die CAW-Unterstützung manuell aktivieren. Clustered Data ONTAP unterstützt standardmäßig CAW.' 
---
= Aktivieren von CAW auf einem Datastore mithilfe der ESXi CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie in Data ONTAP 7-Mode keine Unterstützung für „Compare and Write“ (CAW) hatten, müssen Sie beim Umstieg auf Clustered Data ONTAP die CAW-Unterstützung manuell aktivieren. Clustered Data ONTAP unterstützt standardmäßig CAW.

* Es dürfen keine I/O oder VMs aktiv auf dem VMFS Datastore ausgeführt werden.
* Der Datastore muss neu eingebunden werden, sofern er migriert wurde.
* Sie müssen die neue ONTAP-LUN-naa-ID aus der 7-Mode Transition Tool (7MTT)-Zuordnungsdatei besitzen.


„CAW“ muss nur aktiviert werden, wenn keine I/O- oder VMs im VMFS-Datastore aktiv ausgeführt werden.

* „CAW“ muss nur aktiviert werden, wenn keine I/O- oder VMs im VMFS-Datastore aktiv ausgeführt werden.
* Führen Sie bei Copy-Based Transitions diese Schritte nach Abschluss des Storage-Umstellungsvorgangs im 7MTT aus.
* Führen Sie bei Copy-Free Transitions die folgenden Schritte aus, nachdem der Vorgang Daten & Konfiguration in 7MTT abgeschlossen ist.


.Schritte
. Öffnen Sie das vom Inventory Collect Tool (ICT) generierte Arbeitsbuch _Inventory Assessment_.
. Navigieren Sie zur Registerkarte SAN-Host-Dateisysteme.
. Überprüfen Sie den CAW-Status für den Datastore.
+
Der *ATS/CAW*-Wert für den Datastore sollte *deaktivierte* und die Filesystem-Spalte sollte *VMFS.x* angezeigt werden.

. Notieren Sie sich den Namen des Datenspeichers in der Spalte „Festplatte“
. Melden Sie sich über SSH bei der ESXi Konsole an.
. Listen Sie die Geräte- und Partitionsdetails auf:
+
`*~ # vmkfstools -Ph -v1 _datastore_path_*`

+
Datastore_PATH ist der Name des Datenspeichers aus der Spalte „Disk“ des Arbeitsbuchs zur Bestandsaufnahme_.

+
`*# vmkfstools -Ph -v1 /vmfs/volumes/datastorename*`

+
[listing]
----
VMFS-5.60 file system spanning 1 partitions.
File system label (if any): datastorename
Mode: public
Capacity 9.8 GB, 8.2 GB available, file block size 1 MB, max file size 64
TB
Volume Creation Time: Mon Dec 9 10:29:18 2013
Files (max/free): 27408/27394
Ptr Blocks (max/free): 64512/64495
Sub Blocks (max/free): 3968/3964
Secondary Ptr Blocks (max/free): 256/256
File Blocks (overcommit/used/overcommit %): 0/1593/0
Ptr Blocks (overcommit/used/overcommit %): 0/17/0
Sub Blocks (overcommit/used/overcommit %): 0/4/0
Volume Metadata size: 590675968
UUID: 52a59b7e-52d2fb6c-11d6-001ec9d631cb
Partitions spanned (on "lvm"):
naa.600a098044314c6c442b446d51376749:1
naa.600a098054314c6c445d446f79716431:1
naa.600a098054314c6c445d446f79716433:1
Is Native Snapshot Capable: YES
----
. Notieren Sie den ersten Gerätenamen und die Partitionsnummer.
+
Im vorhergehenden Beispiel `naa.600a098044314c6c442b446d51376749:1` Ist der Gerätename und die Partitionsnummer.

. Verwenden Sie die Geräte-ID und die Partitionsnummer, um CAW auf dem Datastore zu aktivieren:
+
`*~# vmkfstools --configATSOnly 1 /vmfs/devices/disks/__device-ID:Partition__*`

. Überprüfen Sie, ob das VMFS-Volume nur mit ATS konfiguriert wurde:
+
`*# vmkfstools -Ph -v1 /vmfs/volumes/VMFS-volume-name*`

+
[listing]
----
VMFS-5.54 file system spanning 1 partitions.
File system label (if any): ats-test-1
Mode: public ATS-only
----


*Verwandte Informationen*

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[NeuMounten von VMFS-Volumes nach dem Umstieg mit vSphere Client]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[NeuMounten von VMFS-Volumes nach dem Übergang mit der ESXi CLI]

https://["VMware Dokumentation"]
