---
permalink: san-host/task_preparing_to_transition_san_boot_luns_on_aix_hosts_with_fc_fcoe_configurations.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, san, boot, lun, aix, host, fc, fcoe 
summary: Bevor Sie eine SAN Boot LUN auf einem AIX-Host mit einer FC/FCoE-Konfiguration umstellen, müssen Sie den Namen der 7-Mode LUN, auf der AIX installiert ist, sowie den SCSI-Gerätenamen für diese LUN notieren. 
---
= Vorbereitung der Umstellung von SAN Boot LUNs auf AIX Hosts mit FC/FCoE Konfigurationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine SAN Boot LUN auf einem AIX-Host mit einer FC/FCoE-Konfiguration umstellen, müssen Sie den Namen der 7-Mode LUN, auf der AIX installiert ist, sowie den SCSI-Gerätenamen für diese LUN notieren.

. Bestimmen Sie von der Konsole Ihres Data ONTAP 7-Mode Controllers den 7-Mode LUN-Namen, auf dem AIX 7.1 und AIX 6.1 Betriebssystem installiert sind:
+
`*lun show*`

. Ermitteln Sie den SCSI-Gerätenamen für die LUN auf dem Host:
+
`*sanlun lun show*`

+
Im folgenden Beispiel lautet die Transition LUN `lun_sanboot_fas3170_aix04` Und das SCSI-Gerät für diese LUN lautet `hdisk0`.

+
[listing]
----
[04:02 AM root@822-aix03p1/]: sanlun lun show
controller[7mode]/
vserver[Cmode] lun-pathname
---------------------------------------------------------------------
fas3170-aix04  /vol/vol_fas3170_aix04_sanboot/lun_sanboot_fas3170_aix04
kit            /vol/kit/kit_0
kit            /vol/kit/kit_0
filename	adapter	protocol	size		mode
-------------------------------------
hdisk0     fcs0       FCP      100g	  7
hdisk1     fcs0       FCP      5g       C
hdisk2     fcs0       FCP      5g       C
----

