---
permalink: san-host/task_mounting_solaris_host_luns_with_zfs_file_systems_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, solaris, host, lun, zfs, file, system 
summary: Nach dem Übergang von Solaris Host-LUNs mit ZFS-Dateisystemen von Data ONTAP im 7-Mode zu Clustered Data ONTAP müssen Sie die LUNs mounten. 
---
= Installieren von Solaris Host-LUNs mit ZFS-Dateisystemen nach der Umstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Übergang von Solaris Host-LUNs mit ZFS-Dateisystemen von Data ONTAP im 7-Mode zu Clustered Data ONTAP müssen Sie die LUNs mounten.

Bei Copy-Based Transitions führen Sie diese Schritte nach Abschluss des Storage-Umstellungsvorgangs im 7-Mode Transition Tool (7MTT) durch.

Bei Copy-Free Transitions führen Sie die folgenden Schritte aus, nachdem der Vorgang Daten und Konfiguration im 7MTT importiert wurde.

. Nutzen Sie die Neuerdeckung Ihrer neuen Clustered Data ONTAP LUNs durch erneutes Scannen des Hosts.
+
.. Identifizieren Sie die FC-Host-Ports (Typ fc-Fabric): +
`*#cfgadm –l*`
.. Heben Sie die Konfiguration des ersten fc-Fabric-Ports ab: +
`*#cfgadm –c unconfigure c1*`
.. Zweiten fc-Fabric-Port herausfinden: +
`*#cfgadm –c unconfigure c2*`
.. Wiederholen Sie die Schritte für andere fc-Fabric-Ports.
.. Überprüfen Sie, ob die Informationen über die Host-Ports und ihre angeschlossenen Geräte korrekt sind: +
`*# cfgadm –al*`
.. Treiber neu laden: +
`*# devfsadm –Cv*`
`*# devfsadm –i iscsi*`


. Überprüfen Sie, ob die LUNs für Clustered Data ONTAP erkannt wurden:
+
`*sanlun lun show*`** Die `lun-pathname` Die Werte für Clustered Data ONTAP LUNs sollten dieselben sein wie für `lun-pathname` Werte für die 7-Mode LUNs vor der Transition. ** Die `mode` Die Spalte sollte „`C`“ anstelle von „`7`“ anzeigen.

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
vs_sru17_5           /vol/zfs/zfs2    /dev/rdsk/c5t600A0980383030444D2B466542485935d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/zfs/zfs1    /dev/rdsk/c5t600A0980383030444D2B466542485934d0s2 scsi_vhci0 FCP        6g      C
vs_sru17_5           /vol/ufs/ufs2    /dev/rdsk/c5t600A0980383030444D2B466542485937d0s2 scsi_vhci0 FCP        5g      C
vs_sru17_5           /vol/ufs/ufs1    /dev/rdsk/c5t600A0980383030444D2B466542485936d0s2 scsi_vhci0 FCP        5g      C
----
. Suchen Sie nach zpools, die zum Importieren verfügbar sind:
+
`*zpool import*`

+
[listing]
----
# zpool import
  pool: n_vg
    id: 3605589027417030916
 state: ONLINE
action: The pool can be imported using its name or numeric identifier.
config:

        n_vg                                     ONLINE
          c0t600A098051763644575D445443304134d0  ONLINE
          c0t600A098051757A46382B445441763532d0  ONLINE
----
. Importieren Sie die zpools, die für den Übergang nach Poolnamen oder mit der Pool-ID verwendet wurden:
+
** `*zpool import _pool-name_*`
** `*zpool import _pool-id_*`


+
[listing]
----
# zpool list
no pools available

# zpool import
  pool: n_pool
    id: 5049703405981005579
 state: ONLINE
action: The pool can be imported using its name or numeric identifier.
config:

        n_pool                                   ONLINE
          c0t60A98000383035356C2447384D396550d0  ONLINE
          c0t60A98000383035356C2447384D39654Ed0  ONLINE

# zpool import n_pool
----
+
+

+
[listing]
----
# zpool import 5049703405981005579

[59] 09:55:53 (root@sunx2-shu04) /tmp
# zpool list
NAME     SIZE  ALLOC   FREE  CAP  HEALTH  ALTROOT
n_pool  11.9G  2.67G  9.27G  22%  ONLINE  -
----
. Überprüfen Sie, ob das zpool online ist, indem Sie eine der folgenden Aktionen ausführen:
+
** `*zpool status*`
** `*zpool list*`


+
[listing]
----
# zpool status
  pool: n_pool
 state: ONLINE
 scan: none requested
config:

        NAME                                     STATE     READ WRITE CKSUM
        n_pool                                   ONLINE       0     0     0
          c0t60A98000383035356C2447384D396550d0  ONLINE       0     0     0
          c0t60A98000383035356C2447384D39654Ed0  ONLINE       0     0     0

errors: No known data errors
----
+
+

+
[listing]
----
# zpool list
NAME     SIZE  ALLOC   FREE  CAP  HEALTH  ALTROOT
n_pool  11.9G  2.67G  9.27G  22%  ONLINE  -
----
. Überprüfen Sie die Mount-Punkte mit einem der folgenden Befehle:
+
** `*zfs list*`
** `*df –ah*`


+
[listing]
----
# zfs list
NAME           USED  AVAIL  REFER  MOUNTPOINT
n_pool        2.67G  9.08G   160K  /n_pool
n_pool/pool1  1.50G  2.50G  1.50G  /n_pool/pool1
n_pool/pool2  1.16G  2.84G  1.16G  /n_pool/pool2

#df –ah
n_pool                  12G   160K   9.1G     1%    /n_pool
n_pool/pool1           4.0G   1.5G   2.5G    38%    /n_pool/pool1
n_pool/pool2           4.0G   1.2G   2.8G    30%    /n_pool/pool2
----

