---
permalink: san-host/task_replacing_7_mode_wwids_on_linux_host_after_transition_of_luns.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, 7, mode, wwids, linux, lun 
summary: Nach der LUN-Umstellung ändert sich die 7-Mode LUN WWID. Sie müssen sie durch die entsprechende WWID der ONTAP-LUN ersetzen, bevor Sie mit dem Daten-Service beginnen können. 
---
= Ersatz von 7-Mode LUN WWIDs auf Linux Hosts nach der Transition von LUNs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach der LUN-Umstellung ändert sich die 7-Mode LUN WWID. Sie müssen sie durch die entsprechende WWID der ONTAP-LUN ersetzen, bevor Sie mit dem Daten-Service beginnen können.

Wenn Sie eine Copy-Free Transition (CFT) durchführen, müssen Verfahren für Volume Rehosting abgeschlossen sein.

Siehe link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html["Copy-Free Transition Guide Für 7-Mode Transition Tool"]Entsprechende Details.

* Führen Sie bei Copy-Based Transitions (CBTs) diese Schritte nach Abschluss des Storage-Umstellungsvorgangs im 7MTT aus.
* Führen Sie bei CFTs diese Schritte aus, nachdem der Vorgang Daten & Konfiguration im 7MTT importiert wurde.


.Schritte
. Erzeugen der LUN-Zuordnungsdatei für 7-Mode zu ONTAP:
+
** Führen Sie für CBTs den folgenden Befehl auf dem Linux-Host aus, auf dem 7MTT installiert ist: +
`*transition cbt export lunmap -p project-name -o _file_path_*`
+
Beispiel:

+
`*transition cbt export lunmap -p SanWorkLoad -o c:/Libraires/Documents/7-to-C-LUN-MAPPING.csv*`

** Führen Sie bei CFTs den folgenden Befehl auf dem System aus, auf dem das 7MTT installiert ist: +
`*transition cft export lunmap -p _project-name_ -s _svm-name_ -o _output-file_*`
+
Beispiel:

+
`*transition cft export lunmap -p SanWorkLoad -s svml -0 c:/Libraries/Documents/7-to-C-LUN-MAPPING-svml.csv*`

+

NOTE: Sie müssen diesen Befehl für jede Ihrer Storage Virtual Machines (SVMs) ausführen.



. Notieren Sie sich die neue Handle-ID für das ONTAP-LUN-Gerät aus der LUN-Zuordnungsdatei.
. Entfernen Sie die für 7-Mode LUNs erstellten SCSI-Geräte:
+
** So entfernen Sie alle SCSI-Geräte: +
`*rescan-scsi-bus.sh -r*`
** So entfernen Sie jedes SCSI-Gerät einzeln: +
`*echo 1> /sys/block/__SCSI_ID__/delete*`
+
Dieser Befehl muss auf allen 7-Mode LUN SCSI-Geräten ausgeführt werden. In der Spalte SCSI Device ID auf der Registerkarte SAN Host LUNs im Arbeitsbuch _Inventory Assessment_ finden Sie die SCSI-Geräte-IDs für die LUNs.



. Neue ONTAP LUNs ermitteln:
+
`*rescan-scsi-bus.sh*`

. Identifizieren Sie die SCSI-Geräte der neuen ONTAP-LUNs:
+
`*sanlun lun show*`

. Holen Sie sich die WWIDs der neuen ONTAP LUNs:
+
`*/lib/udev/scsi_id -g -u -d /dev _SCSI_dev_*`

. Wenn ein DMMP-Alias definiert ist, aktualisieren Sie die Datei /etc/Multipath.conf, um die 7-Mode LUN WWID durch die entsprechende ONTAP LUN WWID zu ersetzen, so dass der DMMP-Alias auf die Clustered Data ONTAP-LUN verweist:
+
`*cat /etc/multipath.conf*`

. Konfigurieren der DMMP-Geräte:
+
`*multipath*`

. Überprüfen Sie, ob der DMMP-Alias korrekt auf die WWID der ONTAP-LUN verweist:
+
`*multipath -11*`

+
In der folgenden Beispielausgabe wird der DMMP-Alias angezeigt `dmmp_raw_lun` Referenzierung läuft `3600a098051764b2d4f3f453135452d31` Als ONTAP WWID:

+
[listing]
----
root@IBMx3550M3-229-169 ~]# multipath -ll dmmp_raw_lun
dmmp_raw_lun (3600a098051764b2d4f3f453135452d31) dm-8 NETAPP, LUN C-Mode
[size=1.0G] [features=3 queue_if_no_path pg_init_retries 50] [hwhandler=1 alua] [rw]
\_round-robin 0 [prio=50][enabled]
 \_5:0:0:6 sdx 	65:112 [active][ready]
	\_8:0:0:6 sdab 65:176 [active][ready]
\_round-robin 0 [prio=10][enabled]
 \_6:0:0:6 sdy 	65:128 [active][ready]
	\_7:0:0:6 sdaa 65:160 [active][ready]
----

