---
permalink: san-host/task_testing_transitioned_san_boot_luns_on_aix_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, boot, lun, aix, hosts, cutover, phase, copy, based 
summary: 'Wenn Sie für die Transition Ihrer 7-Mode Windows Host-LUNs mit dem 7-Mode Transition Tool \(7MTT\) 2.2 oder höher und Data ONTAP 8.3.2 oder höher verwenden, können Sie Ihre überstiegenen Clustered Data ONTAP LUNs vor der Umstellungsphase testen, um zu überprüfen, ob sie nach Bedarf funktionieren.' 
---
= Die Tests übergegangen sind SAN Boot LUNs auf AIX-Hosts vor der Umstellungsphase bei auf Kopien basierenden Übergängen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie zur Transition Ihrer 7-Mode Windows Host LUNs mit dem 7-Mode Transition Tool (7MTT) 2.2 oder höher und mit Data ONTAP 8.3.2 oder höher die Transition durchführen, können Sie vor der Umstellungsphase Ihre Clustered Data ONTAP LUNs testen, um zu überprüfen, ob sie nach Bedarf funktionieren.

Ihre 7-Mode LUNs müssen bereit für den Umstieg sein.

Sie sollten die Hardwareparität zwischen dem Testhost und dem Quell-Host beibehalten, und Sie sollten auf dem Testhost die folgenden Schritte durchführen.

Die Clustered Data ONTAP LUNs befinden sich während des Tests im Lese-/Schreibmodus. Sie werden in den schreibgeschützten Modus umgewandelt, wenn die Tests abgeschlossen sind und Sie die Umstellungsphase vorbereiten.

.Schritte
. Wählen Sie nach Abschluss der Basiskopie in der 7MTT Benutzeroberfläche *Testmodus* aus.
. Klicken Sie in der 7MTT UI auf *Apply Configuration*.
. Melden Sie sich auf dem Testhost bei der Hardware Management Console an, und starten Sie dann Ihren Host im Menü *SMS*.
. Ändern Sie nach dem Booten des Hosts die IP-Adresse und den Hostnamen.
. Vergewissern Sie sich, dass die Clustered Data ONTAP LUNs vorhanden sind:
+
`*sanlun lun show*`

. Führen Sie Ihre Tests nach Bedarf durch.
. Fahren Sie den Testhost herunter:
+
`*shutdown -h*`

. Klicken Sie in der 7MTT Benutzeroberfläche auf *Fertigstellen testen*.


Wenn die Clustered Data ONTAP LUNs Ihrem Quell-Host neu zugeordnet werden sollen, müssen Sie den Quell-Host auf die Umstellungsphase vorbereiten. Wenn die geclusterten Data ONTAP LUNs Ihrem Testhost zugeordnet bleiben sollen, sind keine weiteren Schritte auf dem Testhost erforderlich.
