---
permalink: copy-based/concept_considerations_for_local_users_and_groups_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, cifs, local, users, groups 
summary: Bei der Migration von lokalen CIFS-Benutzern und -Gruppen müssen Sie jedoch unbedingt beachten, dass bei der Migration der Transition eine wichtige Voraussetzung ist. 
---
= Überlegungen für den Übergang von lokalen CIFS-Benutzern und -Gruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Migration von lokalen CIFS-Benutzern und -Gruppen müssen Sie jedoch unbedingt beachten, dass bei der Migration der Transition eine wichtige Voraussetzung ist.

* Wenn im Ziel-Cluster Clustered Data ONTAP 8.2 ausgeführt wird, sollte nicht für 7-Mode Volumes versucht werden, die CIFS-Daten bereitstellen und auf die lokale Benutzer und Gruppen zugreifen.
+
Das 7-Mode Transition Tool unterstützt den Übergang von lokalen Benutzern und Gruppen zu Clustered Data ONTAP 8.2 nicht.

* Umstellung von CIFS Datenservice-Volumes von einem 7-Mode Controller oder einer vFiler Einheit mit lokalen Benutzern und Gruppen auf eine SVM mit lokalen nicht-BUILTIN CIFS lokalen Benutzern und Gruppen wird nicht unterstützt.
+
Für den Übergang muss die SVM nur lokale BUILTIN CIFS Benutzer und Gruppen haben.

+
Während die Umstellung lokaler Benutzer und Gruppen von einem bestimmten 7-Mode Controller oder einer vFiler Einheit auf eine bestimmte SVM ermöglicht wird, werden lokale Benutzer und Gruppen vom ersten Übergangsprojekt verschoben. Bei der darauffolgenden Umstellung von Projekten mit demselben 7-Mode Controller oder derselben vFiler Einheit auf dieselbe SVM wird die Umstellung von lokalen Benutzern und Gruppen ignoriert, auch wenn der Wechsel erfolgreich ist. Der Name des lokalen Benutzers auf dem 7-Mode System darf nicht mit dem CIFS-Servernamen auf der SVM übereinstimmen.

* Beachten Sie die Beschränkungen für die Anzahl der lokalen Benutzer und Gruppen, die in Clustered Data ONTAP 8.2.1 und höher unterstützt werden.
* Ein lokales Benutzerkonto mit einem leeren Passwort oder lokalen Benutzerkonten mit Kennwörtern, die mehr als 14 Zeichen im 7-Mode-System enthalten, wird in die ONTAP-Software mit dem Passwort übertragen `*cifsUser@1*`.
+
Nach Abschluss der Umstellung können Sie über das Windows-System über das Kennwort auf diese Benutzer zugreifen `*cifsUser@1*`. Sie müssen dann das Passwort für diese lokalen CIFS-Benutzer auf der SVM mit dem folgenden Befehl manuell ändern:

+
`*cifs users-and-groups local-user set-password -vserver _svm_name_ -user-name _user_name_*`.

* Wenn die IP-Adresse des 7-Mode Transition Tools nicht über die Ziel-ONTAP-Software erreichbar ist, blockiert das 7-Mode Transition Tool den Übergang von lokalen CIFS-Benutzern und -Gruppen zur ONTAP-Software während der Vorprüfphase. Wenn dieser Fehler während der Vorprüfphase auftritt, verwenden Sie den
+
`*network ping -node local -destination _ip_address_*`

+
Befehl, um sicherzustellen, dass die IP-Adresse des 7-Mode Transition Tools über die Ziel-ONTAP-Software erreichbar ist. Sie können die bearbeiten `\etc\conf\transition-tool.conf` Datei, die mit dem 7-Mode Transition Tool installiert wird, um jede Konfigurationsoption, die vom Tool verwendet wird, zu ändern, z. B. die IP-Adresse des 7-Mode Transition Tools.

* Die SVM, zu der die lokalen Benutzer und Gruppen migriert werden, muss über eine Daten-LIF verfügen.
* Wenn eine lokale Gruppe mehrere Mitglieder-System-IDs (SIDs) einem einzelnen Domänenbenutzer oder einer Gruppe auf dem 7-Mode-System zugeordnet hat, blockiert das 7-Mode Transition Tool den Übergang von lokalen Benutzern und Gruppen zu ONTAP während der Vorprüfphase.
+
Wenn dieser Fehler während der Vorprüfphase auftritt, müssen Sie die zusätzlichen SIDs manuell entfernen, die einem einzelnen Domain-Benutzer oder einer einzelnen Gruppe auf dem 7-Mode-System zugeordnet sind. Anschließend müssen Sie die Vorabprüfung mit nur einem einzigen SID wiederholen, der dem Domänenbenutzer oder der Gruppe zugeordnet ist.

+
https://["Fehlerbehebung Workflow: CIFS: Das an das System angeschlossene Gerät funktioniert nicht"]



*Verwandte Informationen*

http://["SMB/CIFS-Management"]
