---
permalink: copy-based/concept_considerations_for_space_when_transitioning_san_volumes.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, space, considerations, san, volumes 
summary: Sie müssen sicherstellen, dass während des Übergangs ausreichend Speicherplatz in den Volumes verfügbar ist. Neben dem benötigten Platz zum Speichern von Daten und Snapshot Kopien benötigt der Umstiegsprozess auch 1 MB Speicherplatz pro LUN zur Aktualisierung bestimmter Dateisystem-Metadaten. 
---
= Überlegungen zu Speicherplatz beim Umstieg von SAN-Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen sicherstellen, dass während des Übergangs ausreichend Speicherplatz in den Volumes verfügbar ist. Neben dem benötigten Platz zum Speichern von Daten und Snapshot Kopien benötigt der Umstiegsprozess auch 1 MB Speicherplatz pro LUN zur Aktualisierung bestimmter Dateisystem-Metadaten.

Vor der Umstellung können Sie das verwenden `df -h` Befehl auf dem 7-Mode Volume, um zu überprüfen, ob freier Speicherplatz von 1 MB pro LUN im Volume verfügbar ist. Das Volume sollte außerdem freien Speicherplatz aufweisen, der der Datenmenge entspricht, die voraussichtlich vor der endgültigen Umstellung auf das Volume geschrieben werden soll. Wenn das Volume nicht über genügend freien Speicherplatz verfügt, muss dem 7-Mode-Volume der erforderliche Speicherplatz hinzugefügt werden.

Wenn der Übergang von LUNs aufgrund von mangelndem Platz auf dem Ziel-Volume fehlschlägt, wird die folgende EMS-Nachricht generiert: `LUN.vol.proc.fail.no.space: Processing for LUNs in volume vol1 failed due to lack of space`.

In diesem Fall müssen Sie die einstellen `filesys-size-fixed` Attribut auf `false` Auf dem Zieldatenträger, und dann 1 MB pro LUN freien Speicherplatz zum Volumen hinzufügen.

Wenn es Volumes gibt, die Platz-reservierte LUNs enthalten, kann das Volumen um 1 MB pro LUN wachsen, sodass möglicherweise nicht ausreichend Speicherplatz zur Verfügung steht. In solchen Fällen muss der zusätzliche Speicherplatz hinzugefügt werden, die Größe der Snapshot-Reserve für das Volume ist. Nachdem dem Ziel-Volume Speicherplatz hinzugefügt wurde, können Sie den verwenden `lun transition start` Befehl zum Umstellen der LUNs.

*Verwandte Informationen*

http://docs.netapp.com/ontap-9/index.jsp["NetApp Dokumentation: ONTAP 9"]
