---
permalink: copy-based/task_starting_data_copy_for_a_transition_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, data, copy, project 
summary: Sie können eine Datenkopie von 7-Mode Volumes auf ONTAP Volumes starten, um einen Basistransfer zu erstellen. Der Basistransfer beginnt, wenn die in einem Projekt konfigurierten Zeitpläne für die Datenkopieerstellung aktiv werden. Nach Abschluss des Basistransfers werden die ONTAP Volumes regelmäßig basierend auf dem Zeitplan der Datenkopieerstellung aktualisiert. 
---
= Datenkopie für ein Übergangsprojekt starten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Datenkopie von 7-Mode Volumes auf ONTAP Volumes starten, um einen Basistransfer zu erstellen. Der Basistransfer beginnt, wenn die in einem Projekt konfigurierten Zeitpläne für die Datenkopieerstellung aktiv werden. Nach Abschluss des Basistransfers werden die ONTAP Volumes regelmäßig basierend auf dem Zeitplan der Datenkopieerstellung aktualisiert.

* Sie müssen eine Vorprüfung für das Projekt ausführen und alle Fehler beheben.
* Sie benötigen ein dediziertes Netzwerk mit hoher Bandbreite und niedriger Latenz zwischen den Quell- und Zielsystemen für den Datentransfer.
+

NOTE: Mit SnapMirror Multipathing können Sie die Datentransferlast zwischen den beiden Pfaden ausgleichen.

* Für die Sitzung muss ein Zeitplan für die Datenkopieerstellung konfiguriert werden.


Wenn Sie einen Wechsel zu einer vorhandenen SVM durchführen, werden die Volumes bei diesem Vorgang erstellt. Wenn Sie einen Wechsel zu einer neuen SVM durchführen, werden die SVM und ihre Volumes während dieses Vorgangs erstellt.

SnapMirror Beziehungen werden zwischen 7-Mode und ONTAP Volumes erstellt.

.Schritte
. Starten der Datenkopie:
+
`*transition start -p _project_name_*`

+
Wenn der Startvorgang fehlschlägt und die Datenkopie nicht gestartet wird, müssen Sie die Probleme beheben und den ausführen `transition start` Befehl erneut.

+
[listing]
----
7-Mode Transition Tool>transition start -p project_finance

[1/17 ] Project status checks                                      [      Ok       ]
[2/17 ] Validating 7-Mode system information                       [      Ok       ]
[3/17 ] Validating 7-Mode volumes information                      [      Ok       ]
[4/17 ] Validating Cluster-Mode system information                 [      Ok       ]
[5/17 ] Validating Cluster-Mode volume information                 [      Ok       ]
[6/17 ] Validating LIF information                                 [ Notifications ]
[7/17 ] WAFL prechecks                                             [      Ok       ]
[8/17 ] UNIX users and groups prechecks                            [   Warnings    ]
[9/17 ] SnapMirror prechecks                                       [ Notifications ]
[10/17] NFS prechecks                                              [   Warnings    ]
[11/17] Networking prechecks                                       [ Notifications ]
[12/17] CIFS prechecks                                             [   Warnings    ]
[13/17] Name services prechecks                                    [   Warnings    ]
[14/17] SAN prechecks                                              [      Ok       ]
[15/17] Creating Cluster-Mode volumes                              [      Ok       ]
[16/17] Establishing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]
[17/17] Initializing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]

Operation summary:
------------------
The 'start' operation is completed with warnings and notifications.

 0  Errors - No action required
22  Warnings - Need your attention!
16  Notifications - Please review
102  Informational messages

Do you want to see a detailed report {yes, no} [yes]:

22 Warnings:
------------
20362: Checking whether 7-Mode UNIX groups' names are in use in the Vserver 'vs2'.  [    Warning    ]
  > The following 7-Mode UNIX groups' names are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }

20372: Checking whether 7-Mode UNIX groups' ids are in use in the Vserver 'vs2'.    [    Warning    ]
  > The following 7-Mode UNIX groups' ids are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }
----
+
Das Projekt wechselt in den Status „Copy-Baseline“. Nach Abschluss des Basistransfers wechselt das Projekt in den Status „Copy-Update“.


