---
permalink: copy-based/task_aborting_a_subproject.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, abort, project 
summary: Möglicherweise möchten Sie ein ausgeführten Projekt abbrechen, z. B. wenn sich die Performance des Controllers oder des Clusters auswirkt. Sie können ein laufende Projekt aus dem Dashboard abbrechen. 
---
= Abbrechen eines Projekts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise möchten Sie ein ausgeführten Projekt abbrechen, z. B. wenn sich die Performance des Controllers oder des Clusters auswirkt. Sie können ein laufende Projekt aus dem Dashboard abbrechen.

Folgende Punkte müssen vor dem Abbrechen von Projekten, die Volumes mit SnapMirror Beziehungen verschieben, berücksichtigt werden:

* Wurden beide Projekte gestartet, wird das zugehörige Projekt durch Abbruch eines Projekts abgebrochen.
+
Wenn Sie beispielsweise ein Primärprojekt abbrechen, wird auch das sekundäre Projekt abgebrochen.

* Wenn der Abbruchvorgang beim aktuellen Projekt fehlschlägt, wird das zugeordnete Projekt nicht abgebrochen.
* Wenn nur ein aktives Projekt abgebrochen wird, schlägt der Startvorgang für das zugehörige Projekt fehl.
* Wenn Sie ein primäres Projekt abbrechen, wird der Kopiervorgang vom primären 7-Mode-Volume zum sekundären ONTAP-Volume nicht abgebrochen.
+
Nur der Kopiervorgang vom primären 7-Mode Volume zum entsprechenden primären ONTAP Volume wird abgebrochen.




NOTE: Wenn das 7-Mode-Projekt abgebrochen wird, besteht die einzige Option darin, das Projekt zu löschen. Es ist nicht möglich, das Projekt nach dem Abbruch wieder aufzunehmen oder neu zu starten.

.Schritte
. Wählen Sie im Dashboard das Projekt aus, das abgebrochen werden soll.
. Klicken Sie Auf *Abbrechen*.
. Löschen Sie im Cluster die ONTAP Volumes, die im Rahmen der Transition erstellt wurden.
. Lassen Sie vom 7-Mode System die SnapMirror Beziehungen zu den ONTAP Volumes los.
. Wenn Sie eine Volume-SnapMirror-Beziehung abbrechen, müssen Sie Folgendes durchführen:
+
.. Unterbrechen und Löschen der SnapMirror Beziehung zwischen den primären 7-Mode Volumes und sekundären ONTAP Volumes
.. Lassen Sie vom primären 7-Mode System die SnapMirror Beziehungen zu den sekundären ONTAP Volumes los.




http://["ONTAP 9-Befehle"]

https://["Data ONTAP 8 2 Befehle: Manuelle Seitenreferenz für 7-Mode, Volume 1"]
