---
permalink: copy-based/task_running_precheck_on_a_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, run, prechecks 
summary: Nach Erstellung einer Übergangssitzung können Sie die Sitzung validieren, um zu überprüfen, ob die 7-Mode Umgebung mithilfe des Befehls „Transition Precheck“ migriert werden kann. Sie können die Kompatibilität zwischen dem 7-Mode Storage-System und der SVM für Faktoren wie Features und Sicherheitseinstellungen überprüfen. 
---
= Durchführung von Tests im Vorfeld
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach dem Erstellen einer Übergangssitzung können Sie die Sitzung validieren, um zu überprüfen, ob die 7-Mode Umgebung mithilfe des migriert werden kann `transition precheck` Befehl. Sie können die Kompatibilität zwischen dem 7-Mode Storage-System und der SVM für Faktoren wie Features und Sicherheitseinstellungen überprüfen.

Die Übergangssitzung muss sich im Vorbereitungszustand befinden.

Der `transition cbt precheck` Befehl generiert einen detaillierten Fehlermeldungs-Bericht. Im Bericht identifizierte Probleme werden je nach den Auswirkungen des Problems auf den Übergangsprozess unterschiedlichen Schweregraden zugewiesen. Da einige Fehler die Transition behindern können, müssen Sie Korrekturmaßnahmen für Fehler und Warnungen durchführen. Sie sollten außerdem die Auswirkungen von Meldungen mit anderen Schweregraden überprüfen, bevor Sie mit dem Übergang fortfahren.

.Schritte
. Vergewissern Sie sich, dass die Kompatibilität für den Umstieg besteht:
+
`*transition cbt precheck -p _project_name_*`

+
[listing]
----
7-Mode Transition Tool>transition cbt precheck -p project_finance

[1/14 ] Project status checks                                                  [    Errors     ]

Operation summary:
------------------
The 'precheck' operation on the project 'project_finance' has failed.

 1  Errors - Failed!

Do you want to see a detailed report {yes, no} [yes]:

1 Errors:
---------
90202: Checking whether any of the 7-Mode volumes are in 'offline' state.                              [     Error     ]
  > Following volumes are in 'offline' state.
  > CORRECTIVE-ACTION: Bring offline volumes online by using the following command: 'vol online
  > <volume_name>'.
  > AFFECTED-OBJECTS: { vol2 }

Next suggested steps:
---------------------
1. Review the 'precheck' operation results, fix all blocking errors and run the 'precheck' operation again.
2. Use the 'transition job-results -j 6e33e0a7-bb36-49df-91f3-2e52cbfa3074' command to see the results of this
operation.

Ran precheck for project 'project_finance'.
----


Sie müssen alle Fehler beheben, die bei dem Übergang möglicherweise Probleme verursachen, bevor Sie die Datenkopie aus den 7-Mode Volumes starten.
