---
permalink: install-admin/task_uninstalling_7_mode_transition_tool_on_linux.html 
sidebar: sidebar 
keywords: ontap, 7, mode, install, uninstall, transition, tool, linux 
summary: Sie können das 7-Mode Transition Tool unter Linux über die Befehlszeilenschnittstelle deinstallieren. 
---
= Deinstallieren des 7-Mode Transition Tools unter Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das 7-Mode Transition Tool unter Linux über die Befehlszeilenschnittstelle deinstallieren.

* Sie müssen alle laufenden Übergänge abgeschlossen haben.
+

IMPORTANT: Wenn Sie eine neuere Version installieren oder dieselbe Version des Tools neu installieren, können Sie nicht auf die Übergangsoperationen zugreifen, die von der installierten Instanz gestartet wurden.

* Wenn das 7-Mode Transition Tool ausgeführt wird, muss es gestoppt werden.


JRE wird im Rahmen der Deinstallation nicht entfernt.

.Schritte
. Deinstallieren Sie das 7-Mode Transition Tool, indem Sie den folgenden Befehl aus dem Speicherort ausführen, an dem Sie das 7-Mode Transition Tool extrahiert haben:
+
`*./unconfigure*`

. Entfernen Sie das Verzeichnis des 7-Mode Transition Tool:
+
.. `*cd ..*`
.. `*rm -rf NetApp_7ModeTransitionTool*`






== Beispiel

[listing]
----

bash-4.2# cd /root/Downloads/extracted_folder/NetApp_7ModeTransitionTool
bash-4.2# ./unconfigure
bash-4.2# cd ..
bash-4.2# rm -rf NetApp_7ModeTransitionTool
----