---
permalink: command-map/reference_how_7_mode_options_map_to_clustered_ontap_commands.html 
sidebar: sidebar 
keywords: ontap, command, map, transition, commands, options 
summary: In Data ONTAP 7-Mode führen Sie den Befehl „Optionen“ aus, um konfigurierbare Softwareoptionen für das Storage-System festzulegen. In ONTAP verwenden Sie Befehlsparameter, um diese Optionen festzulegen. Sie können die bereitgestellten Tabellen verwenden, um zu zeigen, wie 7-Mode-Befehle den ONTAP-Befehlen zugeordnet werden. 
---
= Zuordnung der 7-Mode Optionen zu ONTAP Befehlen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Data ONTAP 7-Mode führen Sie die aus `options` Befehl zum Festlegen konfigurierbarer Softwareoptionen für das Storage-System. In ONTAP verwenden Sie Befehlsparameter, um diese Optionen festzulegen. Sie können die bereitgestellten Tabellen verwenden, um zu zeigen, wie 7-Mode-Befehle den ONTAP-Befehlen zugeordnet werden.

In der Spalte „`7-Mode Command`“ wird der Befehl „Basisoptionen“ aus Gründen der Übersichtlichkeit nicht angezeigt. Wo Sie sehen `acp.domain`, Die eigentliche lange Form des Befehls ist Optionen `acp.domain`.

Der Abschnitt „`Understanding the 7-Mode to Clustered Data ONTAP command Mapping`“ enthält Informationen zur Organisation der Tabellen in diesem Kapitel.

xref:concept_how_to_interpret_clustered_ontap_command_maps_for_7_mode_administrators.adoc[Bedeutung der Befehlszuordnung von 7-Mode zu Clustered Data ONTAP]



== A-E

[role="lead"]
*A*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`acp.domain`
 a| 
`*system node run -node {nodename|local} options acp.domain*`



 a| 
`acp.enabled`
 a| 
`*system node run -node {nodename|local} options acp.enabled*`



 a| 
`acp.netmask`
 a| 
`*system node run -node {nodename|local} options acp.netmask*`



 a| 
`acp.port`
 a| 
`*system node run -node {nodename|local} options acp.port*`



 a| 
`auditlog.enable`
 a| 
`security audit`



 a| 
`auditlog.max_file_size`
 a| 
Nicht unterstützt



 a| 
`auditlog.readonly_api.enable`
 a| 
`security audit`



 a| 
`autologout.console.enable`
 a| 
`*system timeout modify -timeout*`



 a| 
`autologout.console.timeout`
 a| 
`*system timeout modify -timeout*`



 a| 
`autologout.telnet.enable`
 a| 
Nicht unterstützt



 a| 
`autologout.telnet.timeout`
 a| 
Nicht unterstützt



 a| 
`autosupport.cifs.verbose`
 a| 
Nicht unterstützt



 a| 
`autosupport.content`
 a| 
`*system node autosupport modify -node _nodename_ -remove -private -data {true|false}*`



 a| 
`autosupport.doit`
 a| 
`*system node autosupport invoke -node _nodename_ -type {all|test}*`



 a| 
`autosupport.enable`
 a| 
`*system node autosupport modify -node _nodename_ -state {enable|disable}*`



 a| 
`autosupport.from`
 a| 
`*system node autosupport modify -node _nodename_ -from*`



 a| 
`autosupport.local_collection`
 a| 
`*system node autosupport modify -node _nodename_ -local-collection {true|false}*`



 a| 
`autosupport.mailhost`
 a| 
`*system node autosupport modify -node _nodename_ -mail-hosts*`



 a| 
`autosupport.max_http_size`
 a| 
`*system node autosupport modify -node _nodename_ -max-http-size*`



 a| 
`autosupport.max_smtp_size`
 a| 
`*system node autosupport modify -node _nodename_ -max-smtp-size*`



 a| 
`autosupport.minimal.subject.id`
 a| 
`*system node autosupport modify -node _nodename_ -hostname-subj*`



 a| 
`autosupport.nht_data.enable` (Nicht in smf)
 a| 
`*autosupport modify -nht*`

`*system node autosupport modify -nht*`



 a| 
`autosupport.noteto`
 a| 
`*system node autosupport modify -node _nodename_ -noteto*`



 a| 
`autosupport.partner.to`
 a| 
`*system node autosupport modify -node _nodename_ -partner-address*`



 a| 
`autosupport.performance_data.doit`
 a| 
`*system node autosupport invoke -node _nodename_ -type performance*`



 a| 
`autosupport.performance_data.enable`
 a| 
`*system node autosupport modify -node _nodename_ -perf {true|false}*`



 a| 
`autosupport.periodic.tx_window`
 a| 
`*system node autosupport modify -node _nodename_ -periodic-tx-window*`



 a| 
`autosupport.retry.count`
 a| 
`*system node autosupport modify -node _nodename_ -retry-count*`



 a| 
`autosupport.retry.interval`
 a| 
`*system node autosupport modify -node _nodename_ -retry-interval*`



 a| 
`autosupport.support.enable`
 a| 
`*system node autosupport modify -node _nodename_ -support {enable|disable}*`



 a| 
`autosupport.support.proxy`
 a| 
`*system node autosupport modify -node _nodename_ -proxy-url*`



 a| 
`autosupport.support.reminder`
 a| 
`*system node autosupport show -node _nodename_ -fields reminder*`



 a| 
`autosupport.support.transport`
 a| 
`*system node autosupport modify -node _nodename_ -transport {http|https|smtp}*`



 a| 
`autosupport.to`
 a| 
`*system node autosupport modify -node _nodename_ -to*`



 a| 
`autosupport.validate_digital_certificate`
 a| 
`*system node autosupport modify -node nodename -validate-digital-certificate {true|false}*`

|===
[role="lead"]
*B*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`backup.log.enable`
 a| 
Nicht unterstützt

|===
[role="lead"]
*C*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`cdpd.enable`
 a| 
`*system node run -node {nodename|local} options cdpd.enable*`



 a| 
`cdpd.holdtime`
 a| 
`*system node run -node {nodename|local} options cdpd.holdtime*`



 a| 
`cdpd.interval`
 a| 
`*system node run -node {nodename|local} options cdpd.interval*`



 a| 
`cf.giveback.auto.after.panic.takeover`
 a| 
`*storage failover modify -auto-giveback-after-panic*`



 a| 
`cf.giveback.auto.cancel.on_network_failure`
 a| 
Nicht unterstützt



 a| 
`cf.giveback.auto.delay.seconds`
 a| 
`*storage failover modify -delay-seconds*`



 a| 
`cf.giveback.auto.enable`
 a| 
`*storage failover modify -auto-giveback*`



 a| 
`cf.hw_assist.enable`
 a| 
`*storage failover modify -hwassist*`



 a| 
`cf.hw_assist.partner.address`
 a| 
`*storage failover modify -hwassist-partner-ip*`



 a| 
`cf.hw_assist.partner.port`
 a| 
`*storage failover modify -hwassist-partner-port*`



 a| 
`cf.mode`
 a| 
`*storage failover modify -mode*`



 a| 
`cf.remote_syncmirror.enable`
 a| 
Nicht unterstützt



 a| 
`cf.sfoaggr_maxtime`
 a| 
`*storage failover modify -aggregate-migration-timeout*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`cf.takeover.change_fsid`
 a| 
Nicht unterstützt



 a| 
`cf.takeover.detection.seconds`
 a| 
`*storage failover modify -detection-time*`



 a| 
`cf.takeover.on_disk_shelf_miscompare`
 a| 
Nicht unterstützt



 a| 
`cf.takeover.on_failure`
 a| 
`*storage failover modify -onfailure*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`cf.takeover.on_network_interface_failure`
 a| 
Nicht unterstützt



 a| 
`cf.takeover.on_network_interface_failure.policy all_nics`
 a| 
Nicht unterstützt



 a| 
`cf.takeover.on_panic`
 a| 
`*storage failover modify -onpanic*`



 a| 
`cf.takeover.on_reboot`
 a| 
`*storage failover modify -onreboot*`



 a| 
`cf.takeover.on_short_uptime`
 a| 
`*storage failover modify -onshort-uptime*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`cifs.LMCompatibilityLevel`
 a| 
`*vserver cifs security modify -lm-compatibility-level*`



 a| 
`cifs.audit.autosave.file.extension`
 a| 
Nicht unterstützt



 a| 
`cifs.audit.autosave.file.limit`
 a| 
`*vserver audit modify -rotate-limit*`



 a| 
`cifs.audit.autosave.onsize.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.audit.autosave.onsize.threshold`
 a| 
Nicht unterstützt



 a| 
`cifs.audit.autosave.ontime.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.audit.autosave.ontime.interval`
 a| 
Nicht unterstützt



 a| 
`cifs.audit.enable`
 a| 
`*vserver audit*`



 a| 
`cifs.audit.file_access_events.enable`
 a| 
`*vserver audit modify -events*`



 a| 
`cifs.audit.nfs.filter.filename`
 a| 
Nicht unterstützt



 a| 
`cifs.audit.logon_events.enable`
 a| 
`*vserver audit modify -events cifs-logon-logoff*`



 a| 
`cifs.audit.logsize`
 a| 
Nicht unterstützt



 a| 
`cifs.audit.nfs.enable`
 a| 
`*vserver audit modify -events file-ops*`



 a| 
`cifs.audit.nfs.filter.filename`
 a| 
Nicht unterstützt



 a| 
`cifs.audit.saveas`
 a| 
`*vserver audit modify -destination*`



 a| 
`cifs.bypass_traverse_checking`
 a| 
`*vserver cifs users-and-groups privilege*`



 a| 
`cifs.comment`
 a| 
`*vserver cifs create -comment*`



 a| 
`cifs.enable_share_browsing`
 a| 
`vserver cifs share`



 a| 
`cifs.gpo.enable`
 a| 
`*vserver cifs group-policy*`



 a| 
`cifs.gpo.trace.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.grant_implicit_exe_perms`
 a| 
`*vserver cifs options modify -read-grant-exec*`



 a| 
`cifs.guest_account`
 a| 
Nicht unterstützt



 a| 
`cifs.home_dir_namestyle`
 a| 
`*vserver cifs share create*`



 a| 
`cifs.home_dirs_public`
 a| 
`*vserver cifs home-directory modify -is-home-dirs-access-for-public-enabled {true|false}*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`cifs.home_dirs_public_for_admin`
 a| 
`*vserver cifs home-directory modify -is-home-dirs-access-for-public-enabled{true|false}*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`cifs.idle_timeout`
 a| 
`*vserver cifs options modify -client-session-timeout*`



 a| 
`cifs.ipv6.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.max_mpx`
 a| 
`*vserver cifs options modify -max-mpx*`



 a| 
`cifs.ms_snapshot_mode`
 a| 
Nicht unterstützt



 a| 
`cifs.mapped_null_user_extra_group`
 a| 
`_vserver cifs options modify -win-name-for-null-user_`



 a| 
`cifs.netbios_over_tcp.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.nfs_root_ignore_acl`
 a| 
`*vserver nfs modify -ignore-nt-acl-for-root*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`cifs.ntfs_ignore_unix_security_ops`
 a| 
`*vserver nfs modify -ntfs-unix-security-ops*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`cifs.oplocks.enable`
 a| 
`vserver cifs share properties add -share-properties`



 a| 
`cifs.oplocks.opendelta*`
 a| 
Nicht unterstützt



 a| 
`cifs.perm_check_ro_del_ok`
 a| 
`*vserver cifs options modify -is-read-only-delete-enabled*`



 a| 
`cifs.perm_check_use_gid`
 a| 
Nicht unterstützt



 a| 
`cifs.restrict_anonymous`
 a| 
`*vserver cifs options modify -restrict-anonymous*`



 a| 
`cifs.save_case`
 a| 
Nicht unterstützt



 a| 
`cifs.scopeid`
 a| 
Nicht unterstützt



 a| 
`cifs.search_domains`
 a| 
`*vserver cifs domain name-mapping-search*`



 a| 
`cifs.show_dotfiles`
 a| 
`is-hide-dotfiles-enabled`



 a| 
`cifs.show_snapshot`
 a| 
`*vserver cifs share properties add -share-properties*`



 a| 
`cifs.shutdown_msg_level`
 a| 
Nicht unterstützt



 a| 
`cifs.signing.enable`
 a| 
`*vserver cifs security modify -is-signing-required*`



 a| 
`cifs.smb2.client.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.smb2.durable_handle.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.smb2.durable_handle.timeout`
 a| 
Nicht unterstützt



 a| 
`cifs.smb2.enable`
 a| 
`*vserver cifs options modify -smb2-enabled*`



 a| 
`cifs.smb2.signing.required`
 a| 
`*vserver cifs security modify -is-signing-required*`



 a| 
`cifs.smb2_1.branch_cache.enable`
 a| 
`*vserver cifs share properties*`



 a| 
`cifs.smb2_1.branch_cache.hash_time_out`
 a| 
Nicht unterstützt



 a| 
`cifs.snapshot_file_folding.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.symlinks.cycleguard`
 a| 
Nicht unterstützt



 a| 
`cifs.symlinks.enable`
 a| 
`*vserver cifs share modify -symlink-properties*`



 a| 
`cifs.universal_nested_groups.enable`
 a| 
Nicht unterstützt



 a| 
`cifs.W2K_password_change`
 a| 
`*vserver cifs domain password change*`



 a| 
`cifs.W2K_password_change_interval`
 a| 
`*vserver cifs domain password change schedule*`



 a| 
`cifs.W2K_password_change_within`
 a| 
`*vserver cifs domain password change schedule*`



 a| 
`cifs.widelink.ttl`
 a| 
Nicht unterstützt



 a| 
`console.encoding`
 a| 
Nicht unterstützt



 a| 
`coredump.dump.attempts`
 a| 
`*system node coredump config modify -coredump-attempts*`



 a| 
`coredump.metadata_only`
 a| 
`*system node coredump config modify -sparsecore-enabled true*`

|===
[role="lead"]
*D*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`disk.asup_on_mp_loss`
 a| 
`*system node autosupport trigger modify dsk.redun.fault*`



 a| 
`disk.auto_assign`
 a| 
`*storage disk option modify -autoassign*`



 a| 
`disk.auto_assign_shelf`
 a| 
`*storage disk option modify -autoassign-shelf*`



 a| 
`disk.maint_center.allowed_entries`
 a| 
Nicht unterstützt



 a| 
`disk.maint_center.enable`
 a| 
`*system node run -node {nodename|local} options disk.maint_center.enable*`



 a| 
`disk.maint_center.max_disks`
 a| 
`*system node run -node {nodename|local} options disk.maint_center.max_disks*`



 a| 
`disk.maint_center.rec_allowed_entries`
 a| 
`*system node run -node {nodename|local} options disk.maint_center.rec_allowed_entries*`



 a| 
`disk.maint_center.spares_check`
 a| 
`*system node run -node {nodename|local} options disk.maint_center.spares_check*`



 a| 
`disk.powercycle.enable`
 a| 
`*system node run -node {nodename|local} options disk.powercycle.enable*`



 a| 
`disk.recovery_needed.count`
 a| 
Nicht unterstützt



 a| 
`disk.target_port.cmd_queue_depth`
 a| 
`*storage array modify -name _array_name_ -max-queue-depth*`



 a| 
`dns.cache.enable`
 a| 
Nicht unterstützt



 a| 
`dns.domainname`
 a| 
`*vserver services name-service dns modify -domains*`



 a| 
`dns.enable`
 a| 
`*vserver services name-service dns modify -state*`



 a| 
`dns.update.enable`
 a| 
Nicht unterstützt



 a| 
`dns.update.ttl`
 a| 
Nicht unterstützt

|===
[role="lead"]
*E*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`ems.autosuppress.enable`
 a| 
`*event config modify -suppression {_on|off_}*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene

|===


== F-K

[role="lead"]
*F*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`fcp.enable`
 a| 
`*fcp start*`



 a| 
`flexcache.access`
 a| 
Nicht unterstützt



 a| 
`flexcache.deleg.high_water`
 a| 
Nicht unterstützt



 a| 
`flexcache.deleg.low_water`
 a| 
Nicht unterstützt



 a| 
`flexcache.enable`
 a| 
Nicht unterstützt



 a| 
`flexcache.per_client_stats`
 a| 
Nicht unterstützt



 a| 
`flexscale.enable`
 a| 
`*system node run -node _node_name_|local} options flexscale.enable*`



 a| 
`flexscale.lopri_blocks`
 a| 
`*system node run -node _node_name_|local} options flexscale.lopri_blocks*`



 a| 
`flexscale.normal_data_blocks`
 a| 
`*system node run -node _node_name_|local} options flexscale.normal_data_blocks*`



 a| 
`flexscale.pcs_high_res`
 a| 
`*system node run -node _node_name_|local} options flexscale.pcs_high_res*`



 a| 
`flexscale.pcs_size`
 a| 
`*system node run -node _node_name_|local} options flexscale.pcs_size*`



 a| 
`flexscale.rewarm`
 a| 
`*system node run -node _node_name_|local} options flexscale.rewarm*`



 a| 
`fpolicy.enable`
 a| 
`*vserver fpolicy enable*`



 a| 
`fpolicy.i2p_ems_interval`
 a| 
Nicht unterstützt



 a| 
`fpolicy.multiple_pipes`
 a| 
Nicht unterstützt



 a| 
`ftpd.3way.enable`
 a| 
Nicht unterstützt



 a| 
`ftpd.anonymous.enable`
 a| 
Nicht unterstützt



 a| 
`ftpd.anonymous.home_dir`
 a| 
Nicht unterstützt



 a| 
`ftpd.anonymous.name`
 a| 
Nicht unterstützt



 a| 
`ftpd.auth_style`
 a| 
Nicht unterstützt



 a| 
`ftpd.bypass_traverse_checking`
 a| 
Nicht unterstützt



 a| 
`ftpd.dir.override`
 a| 
Nicht unterstützt



 a| 
`ftpd.dir.restriction`
 a| 
Nicht unterstützt



 a| 
`ftpd.enable`
 a| 
Nicht unterstützt



 a| 
`ftpd.explicit.allow_secure_data_conn`
 a| 
Nicht unterstützt



 a| 
`ftpd.explicit.enable`
 a| 
Nicht unterstützt



 a| 
`ftpd.idle_timeout`
 a| 
Nicht unterstützt



 a| 
`ftpd.implicit.enable`
 a| 
Nicht unterstützt



 a| 
`ftpd.ipv6.enable`
 a| 
Nicht unterstützt



 a| 
`ftpd.locking`
 a| 
Nicht unterstützt



 a| 
`ftpd.log.enable`
 a| 
Nicht unterstützt



 a| 
`ftpd.log.filesize`
 a| 
Nicht unterstützt



 a| 
`ftpd.log.nfiles`
 a| 
Nicht unterstützt



 a| 
`ftpd.max_connections`
 a| 
Nicht unterstützt



 a| 
`ftpd.max_connections_threshold`
 a| 
Nicht unterstützt



 a| 
`ftpd.tcp_window_size`
 a| 
Nicht unterstützt

|===
[role="lead"]
*H*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`httpd.access`
 a| 
`Not supported`



 a| 
`httpd.admin.access`
 a| 
Nicht unterstützt



 a| 
`httpd.admin.enable`
 a| 
`*vserver services web modify -enabled{true|false}*`



 a| 
`httpd.admin.hostsequiv.enable`
 a| 
Nicht unterstützt



 a| 
`httpd.admin.max_connections`
 a| 
Nicht unterstützt



 a| 
`httpd.admin.ssl.enable`
 a| 
`*security ssl*`



 a| 
`httpd.admin.top-page.authentication`
 a| 
Nicht unterstützt



 a| 
`httpd.bypass_traverse_checking`
 a| 
Nicht unterstützt



 a| 
`httpd.enable`
 a| 
Nicht unterstützt



 a| 
`httpd.ipv6.enable`
 a| 
Nicht unterstützt



 a| 
`httpd.log.format`
 a| 
Nicht unterstützt



 a| 
`httpd.method.trace.enable`
 a| 
Nicht unterstützt



 a| 
`httpd.rootdir`
 a| 
Nicht unterstützt



 a| 
`httpd.timeout`
 a| 
Nicht unterstützt



 a| 
`httpd.timewait.enable`
 a| 
Nicht unterstützt

|===
[role="lead"]
*I*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`ifgrp.failover.link_degraded`
 a| 
Nicht unterstützt



 a| 
`interface.blocked.cifs`
 a| 
`*network interface create -data-protocol*`



 a| 
`interface.blocked.iscsi`
 a| 
`*network interface create -data-protocol*`



 a| 
`interface.blocked.mgmt_data_traffic`
 a| 
`*network interface create -role*`



 a| 
`interface.blocked.ndmp`
 a| 
`*system services firewall policy modify -policy _policy_name_ -service ndmp*`



 a| 
`interface.blocked.nfs`
 a| 
`*network interface create -data-protocol*`



 a| 
`interface.blocked.snapmirror`
 a| 
`*network interface create -role*`



 a| 
`ip.fastpath.enable`
 a| 
`*system node run -node _node_name_|local} options ip.fastpath.enable*`


NOTE: Ab ONTAP 9.2 wird FastPath nicht mehr unterstützt.



 a| 
`ip.ipsec.enable`
 a| 
Nicht unterstützt



 a| 
`ip.match_any_ifaddr`
 a| 
Nicht unterstützt



 a| 
`ip.path_mtu_discovery.enable`
 a| 
`*system node run -node__node_name__|local} options ip.path_mtu_discovery.enable*`



 a| 
`ip.ping_throttle.alarm_interval`
 a| 
`*system node run -node__node_name__ |local} options ip.ping_throttle.alarm___node_name__interval*`



 a| 
`ip.ping_throttle.drop_level`
 a| 
`*system node run -node|local} options ip.ping_throttle.drop.level*`



 a| 
`ip.tcp.abc.enable`
 a| 
`*system node run -node__node_name__|local} options ip.tcp.abc.enable*`



 a| 
`ip.tcp.abc.l_limit`
 a| 
`*system node run -node__node_name__|local} options ip.tcp.abc.l_limit*`



 a| 
`ip.tcp.batching.enable`
 a| 
`*system node run -node__node_name__|local} options ip.tcp.batching.enable*`



 a| 
`ip.tcp.newreno.enable`
 a| 
Nicht unterstützt



 a| 
`ip.tcp.rfc3390.enable`
 a| 
`*system node run -node__node_name__|local} options ip.tcp.rfc3390.enable*`



 a| 
`ip.tcp.sack.enable`
 a| 
`*system node run -node__node_name__|local} options ip.tcp.sack.enable*`



 a| 
`ip.v6.enable`
 a| 
`*network options ipv6 modify*`



 a| 
`ip.v6.ra_enable`
 a| 
Nicht unterstützt



 a| 
`iscsi.auth.radius.enable`
 a| 
Nicht unterstützt



 a| 
`iscsi.enable`
 a| 
`*iscsi start*`



 a| 
`iscsi.max_connections_per_session`
 a| 
`*iscsi modify -max -conn-per-session*`



 a| 
`iscsi.max_error_recovery_level`
 a| 
`*iscsi modify -max-error-recovery-level*`

|===
[role="lead"]
*K*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`kerberos.file_keytab.principal`
 a| 
Nicht unterstützt



 a| 
`kerberos.file_keytab.realmipal`
 a| 
Nicht unterstützt

|===


== O-Q

[role="lead"]
*L*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`ldap.ADdomain`
 a| 
`*vserver services name-service ldap client modify -ad-domain*`



 a| 
`ldap.base`
 a| 
`*vserver services name-service ldap client modify -base-dn*`



 a| 
`ldap.base.group`
 a| 
`*ldap client modify -group-dn ldap DN-group-scope*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.base.netgroup`
 a| 
`*ldap client modify -netgroup-dn ldap DN-netgroup-scope*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.base.passwd`
 a| 
`*vserver services ldap client modify -user-dn*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.enable`
 a| 
`*vserver services name-service ldap modify*`



 a| 
`ldap.minimum_bind_level`
 a| 
`*vserver services name-service ldap client modify -min-bind-level*`



 a| 
`ldap.name`
 a| 
`*vserver services name-service ldap client modify -bind-dn*`



 a| 
`ldap.nssmap.attribute.gecos`
 a| 
`*ldap client schema modify -gecos-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.gidNumber`
 a| 
`*ldap client schema modify -gid-number-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.groupname`
 a| 
`*ldap client schema modify -cn-group-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.homeDirectory`
 a| 
`*ldap client schema modify -home-directory-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.loginShell`
 a| 
`*ldap client schema modify -login-shell-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.memberNisNetgroup`
 a| 
`*ldap client schema modify -member-nis-netgroup-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.memberUid`
 a| 
`*ldap client schema modify -member-uid-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.netgroupname`
 a| 
`*ldap client schema modify -cn-netgroup-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.nisNetgroupTriple`
 a| 
ldap-Client-Schema modify -nis-netgroup-triple-attribut


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.uid`
 a| 
`*ldap client schema modify -uid-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.uidNumber`
 a| 
`*ldap client schema modify -uid-number-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.attribute.userPassword`
 a| 
`*ldap client schema modify -user-password-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.objectClass.nisNetgroup`
 a| 
`*ldap client schema modify -nis-netgroup-object-class*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.objectClass.posixAccount`
 a| 
`*ldap client schema modify -posix-account-object-class*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.nssmap.objectClass.posixGroup`
 a| 
`*ldap client schema modify -posix-group-object-class*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.passwd`
 a| 
`*vserver services name-service ldap client modify-bind-password*`



 a| 
`ldap.port`
 a| 
`*vserver services name-service ldap client modify -port*`



 a| 
`ldap.servers`
 a| 
`*vserver services name-service ldap client modify -servers*`



 a| 
`ldap.servers.preferred`
 a| 
`*vserver services name-service ldap client modify -preferred-ad-servers*`



 a| 
`ldap.ssl.enable`
 a| 
Nicht unterstützt



 a| 
`ldap.timeout`
 a| 
`*vserver services name-service ldap client modify -query-timeout*`



 a| 
`ldap.usermap.attribute.windowsaccount`
 a| 
`*ldap client schema modify -windows-account-attribute*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.usermap.base`
 a| 
`*ldap client modify -user-dnldap DN-user-scope*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ldap.usermap.enable`
 a| 
Nicht unterstützt



 a| 
`licensed_feature.fcp.enable`
 a| 
Nicht unterstützt



 a| 
`licensed_feature.flex_clone.enable`
 a| 
Nicht unterstützt



 a| 
`licensed_feature.flexcache_nfs.enable`
 a| 
Nicht unterstützt



 a| 
`licensed_feature.iscsi.enable`
 a| 
Nicht unterstützt



 a| 
`licensed_feature.multistore.enable`
 a| 
Nicht unterstützt



 a| 
`licensed_feature.nearstore_option.enable`
 a| 
Nicht unterstützt



 a| 
`licensed_feature.vld.enable`
 a| 
Nicht unterstützt



 a| 
`locking.grace_lease_seconds`
 a| 
`*vserver nfs modify -v4-grace-seconds*`



 a| 
`lun.clone_restore`
 a| 
Nicht unterstützt



 a| 
`lun.partner_unreachable.linux.asc`
 a| 
Nicht unterstützt



 a| 
`lun.partner_unreachable.linux.ascq`
 a| 
Nicht unterstützt



 a| 
`lun.partner_unreachable.linux.behavior`
 a| 
Nicht unterstützt



 a| 
`lun.partner_unreachable.linux.hold_time`
 a| 
Nicht unterstützt



 a| 
`lun.partner_unreachable.linux.scsi_status`
 a| 
Nicht unterstützt



 a| 
`lun.partner_unreachable.linux.skey`
 a| 
Nicht unterstützt



 a| 
`lun.partner_unreachable.vmware.behavior`
 a| 
Nicht unterstützt



 a| 
`lun.partner_unreachable.vmware.hold_time`
 a| 
Nicht unterstützt

|===
[role="lead"]
*N*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`ndmpd.abort_on_disk_error`
 a| 
`*options ndmpd.abort_on_disk_error*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`ndmpd.access`
 a| 
`*system services firewall policy modify -policy * -service ndmp -allow-list*`



 a| 
`ndmpd.authtype`
 a| 
`*system services ndmpd modify -clear-text*`



 a| 
`ndmpd.connectlog.enabled`
 a| 
Nicht unterstützt



 a| 
`ndmpd.data_port_range`
 a| 
`Not supported`



 a| 
`ndmpd.enable`
 a| 
Nicht unterstützt



 a| 
`ndmpd.ignore_ctime.enabled`
 a| 
Nicht unterstützt



 a| 
`ndmpd.maxversion`
 a| 
Nicht unterstützt



 a| 
`ndmpd.offset_map.enable`
 a| 
Nicht unterstützt



 a| 
`ndmpd.password_length`
 a| 
Nicht unterstützt



 a| 
`ndmpd.preferred_interface`
 a| 
Nicht unterstützt



 a| 
`ndmpd.tcpnodelay.enable`
 a| 
Nicht unterstützt



 a| 
`ndmpd.tcpwinsize`
 a| 
Nicht unterstützt



 a| 
`nfs.assist.queue.limit`
 a| 
Nicht unterstützt



 a| 
`nfs.authsys.extended_groups_ns.enable`
 a| 
`_vserver nfs modify -auth-sys-extended-groups_`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`nfs.export.allow_provisional_access`
 a| 
Nicht unterstützt



 a| 
`nfs.export.auto-update`
 a| 
Nicht unterstützt



 a| 
`nfs.export.exportfs_comment_on_delete`
 a| 
Nicht unterstützt



 a| 
`nfs.export.harvest.timeout`
 a| 
Nicht unterstützt



 a| 
`nfs.export.neg.timeout`
 a| 
Nicht unterstützt



 a| 
`nfs.kerberos.enable`
 a| 
`*vserver nfs kerberos realm create*`



 a| 
`nfs.kerberos.file_keytab.enable`
 a| 
Nicht unterstützt



 a| 
`nfs.kerberos.file_keytab.principal`
 a| 
`*vserver nfs kerberos realm create*`



 a| 
`nfs.kerberos.file_keytab.realm`
 a| 
`*vserver nfs kerberos realm create*`



 a| 
`nfs.max_num_aux_groups`
 a| 
`*vserver nfs \{ show | modify \} -extended-groups-limit*`



 a| 
`nfs.mount_rootonly`
 a| 
`*vserver nfs modify -mount-rootonly*`



 a| 
`nfs.netgroup.strict`
 a| 
Nicht unterstützt



 a| 
`nfs.nfs_rootonly`
 a| 
`*vserver nfs modify -nfs-rootonly*`



 a| 
`nfs.per_client_stats.enable`
 a| 
`*statistics settings modify -client stats*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`nfs.require_valid_mapped_uid`
 a| 
`*vserver name-mapping create*`



 a| 
`nfs.response.trace`
 a| 
`*vserver nfs modify -trace-enabled*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`nfs.response.trigger`
 a| 
`*vserver nfs modify -trigger*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`nfs.rpcsec.ctx.high`
 a| 
`*nfs modify -rpcsec-ctx-high*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`nfs.rpcsec.ctx.idle`
 a| 
`*nfs modify -rpcsec-ctx-idle*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`nfs.tcp.enable`
 a| 
`*vserver nfs modify -tcp*`



 a| 
`nfs.thin_prov.ejuke`
 a| 
`*vserver nfs modify -enable-ejukebox*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`nfs.udp.enable`
 a| 
`*vserver nfs modify -udp*`



 a| 
`nfs.udp.xfersize`
 a| 
`*vserver nfs modify -udp-max-xfer-size*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`nfs.v2.df_2gb_lim`
 a| 
`wird nicht unterstützt



 a| 
`nfs.v2.enable`
 a| 
`wird nicht unterstützt



 a| 
`nfs.v3.enable`
 a| 
`*vserver nfs modify -v3*`



 a| 
`nfs.v4.acl.enable`
 a| 
`*vserver nfs modify -v4.0-ac*l`



 a| 
`nfs.v4.enable`
 a| 
`*vserver nfs modify -v4.0*`



 a| 
`nfs.v4.id.allow_numerics`
 a| 
`*vserver nfs modify -v4-numeric-ids*`



 a| 
`nfs.v4.id.domain`
 a| 
`*vserver nfs modify -v4-id-domain*`



 a| 
`nfs.v4.read_delegation`
 a| 
`*vserver nfs modify -v4.0-read-delegation*`



 a| 
`nfs.v4.write_delegation`
 a| 
`*vserver nfs modify -v4.0-write-delegation*`



 a| 
`nfs.vstorage.enable`
 a| 
`*vserver nfs modify -vstorage*`



 a| 
`nfs.webnfs.enable`
 a| 
Nicht unterstützt



 a| 
`nfs.webnfs.rootdir`
 a| 
Nicht unterstützt



 a| 
`nfs.webnfs.rootdir.set`
 a| 
Nicht unterstützt



 a| 
`nis.domainname`
 a| 
`*vserver services name-service nis-domain modify -domain*`



 a| 
`nis.enable`
 a| 
`*vserver services name-service nis-domain modify -active*`



 a| 
`nis.group_update.enable`
 a| 
Nicht unterstützt



 a| 
`nis.group_update_schedule`
 a| 
Nicht unterstützt



 a| 
`nis.netgroup.domain_search.enable`
 a| 
Nicht unterstützt



 a| 
`nis.servers`
 a| 
`*vserver services name-service nis-domain modify -servers*`



 a| 
`nis.slave.enable`
 a| 
Nicht unterstützt



 a| 
`nlm.cleanup.timeout`
 a| 
Nicht unterstützt

|===
[role="lead"]
*P*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`pcnfsd.enable`
 a| 
Nicht unterstützt



 a| 
`pcnfsd.umask`
 a| 
Nicht unterstützt

|===
[role="lead"]
*Q*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`qos.classify.count_all_matches`
 a| 
Nicht unterstützt

|===
[role="lead"]
*R*


NOTE: Alle RAID-Optionen haben 7-Mode-kompatible nodeshell Shortcuts des Formulars `options _option_name_`.

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`raid`
 a| 
`*storage raid-options \{ modify | show\}*`



 a| 
`raid.background_disk_fw_update.enable`
 a| 
`*storage disk option modify -bkg-firmware-update*`



 a| 
`raid.disk.copy.auto.enable`
 a| 
`*storage raid-options modify -raid.disk.copy.auto.enable*`



 a| 
`raid.disk.timeout.enable`
 a| 
`*system node run -node {_node_name_|local} options raid.disk.timeout.enable*`



 a| 
`raid.disktype.enable`
 a| 
Nicht unterstützt



 a| 
`raid.disktype.enable`
 a| 
`*raid-options modify raid.lost_write.enable*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`raid.lost_write.enable`
 a| 
`*storage raid-options \{ modify | show \} -name raid.media_scrub.enable*`



 a| 
`raid.media_scrub.rate`
 a| 
`*storage raid-options \{ modify | show \}-name raid.media_scrub.rate*`



 a| 
`raid.min_spare_count`
 a| 
`*storage raid-options \{ modify | show \}-name raid.min_spare_count*`



 a| 
`raid.mix.hdd.disktype.capacity`
 a| 
`*storage raid-options \{ modify | show \}-name raid.mix.hdd.disktype.capacity*`



 a| 
`raid.mix.hdd.disktype.performance`
 a| 
`*storage raid-options \{ modify | show \}-name raid.mix.hdd.disktype.performance*`



 a| 
`raid.mix.hdd.rpm.capacity`
 a| 
`*storage raid-options \{ modify | show \} -name raid.mix.hdd.rpm.capacity*`



 a| 
`raid.mix.hdd.rpm.performance`
 a| 
`*storage raid-options \{ modify | show \} -name raid.mix.hdd.rpm.performance*`



 a| 
`raid.mirror_read_plex_pref`
 a| 
`*storage raid-options \{ modify | show \}-name raid.mirror_read_plex_pref*`



 a| 
`raid.reconstruct.perf_impact`
 a| 
`*storage raid-options \{ modify | show \}-name raid.reconstruct.perf_impact*`



 a| 
`raid.resync.perf_impact`
 a| 
`*storage raid-options \{ modify | show \}-name raid.resync.perf_impact*`



 a| 
`raid.rpm.ata.enable`
 a| 
Nicht unterstützt



 a| 
`raid.rpm.fcal.enable`
 a| 
Nicht unterstützt



 a| 
`raid.scrub.duration`
 a| 
`*storage raid-options \{ modify | show \}-name raid.scrub.duration*`



 a| 
`raid.scrub.perf_impact`
 a| 
`*storage raid-options \{ modify | show \}-name raid.scrub.perf_impact*`



 a| 
`raid.scrub.schedule`
 a| 
`*storage raid-options \{ modify | show \}-name raid.scrub.schedule*`



 a| 
`raid.timeout`
 a| 
`*storage raid-options \{ modify | show \}-name raid.timeout*`



 a| 
`raid.verify.perf_impact`
 a| 
`*storage raid-options\{ modify | show \}-name raid.verify.perf_impact*`



 a| 
`replication.logical.reserved_transfers`
 a| 
`*snapmirror set-options -xdp-source-xfer-reserve-pct*`



 a| 
`replication.throttle.enable`
 a| 
`*snapmirror modify -throttle*`



 a| 
`replication.volume.reserved_transfers`
 a| 
`*snapmirror set-options -dp-source-xfer-reserve-pct*`



 a| 
`replication.volume.use_auto_resync`
 a| 
Nicht unterstützt



 a| 
`rpc.mountd.tcp.port`
 a| 
`*vserver nfs modify -mountd-port*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`rpc.mountd.udp.port`
 a| 
`*vserver nfs modify -mountd-port*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`rpc.nlm.tcp.port`
 a| 
`*vserver nfs modify -nlm-port*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`rpc.nlm.udp.port`
 a| 
`*vserver nfs modify -nlm-port*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`rpc.nsm.tcp.port`
 a| 
`*vserver nfs modify -nsm-port*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`rpc.nsm.udp.port`
 a| 
`*vserver nfs modify -nsm-port*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`rpc.pcnfsd.tcp.port`
 a| 
Nicht unterstützt



 a| 
`rpc.pcnfsd.udp.port`
 a| 
Nicht unterstützt



 a| 
`rpc.rquotad.udp.port`
 a| 
`*vserver nfs modify -rquotad-port*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`rquotad.enable`
 a| 
`*vserver nfs modify -rquota*`



 a| 
`rsh.access`
 a| 
`*system services firewall policy create -policy mgmt -service rsh -allow-list*`



 a| 
`rsh.enable`
 a| 
`*system services firewall policy create -policy mgmt -service rsh -allow-list*`

|===


== S-Z

[role="lead"]
*S*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`security.admin.authentication`
 a| 
`*security login modify*`



 a| 
`security.admin.nsswitchgroup`
 a| 
`*vserver modify*`



 a| 
`security.passwd.firstlogin.enable`
 a| 
`*security login role config modify*`



 a| 
`security.passwd.lockout.numtries`
 a| 
`*security login role config modify*`



 a| 
`security.passwd.rootaccess.enable`
 a| 
Nicht unterstützt



 a| 
`security.passwd.rules.enable`
 a| 
`*security login role config modify*`



 a| 
`security.passwd.rules.everyone`
 a| 
`*security login role config modify*`



 a| 
`security.passwd.rules.history`
 a| 
`*security login role config modify*`



 a| 
`security.passwd.rules.maximum`
 a| 
`*security login role config modify*`



 a| 
`security.passwd.rules.minimum`
 a| 
`*security login role config modify*`



 a| 
`security.passwd.rules.minimum.alphabetic`
 a| 
Nicht unterstützt



 a| 
`security.passwd.rules.minimum.digit`
 a| 
`*security login role config modify*`



 a| 
`security.passwd.rules.minimum.symbol`
 a| 
Nicht unterstützt



 a| 
`sftp.auth_style`
 a| 
Nicht unterstützt



 a| 
`sftp.dir_override`
 a| 
Nicht unterstützt



 a| 
`sftp.dir_restriction`
 a| 
Nicht unterstützt



 a| 
`sftp.enable`
 a| 
Nicht unterstützt



 a| 
`sftp.idle_timeout`
 a| 
Nicht unterstützt



 a| 
`sftp.locking`
 a| 
Nicht unterstützt



 a| 
`sftp.log_enable`
 a| 
Nicht unterstützt



 a| 
`sftp.log_filesize`
 a| 
Nicht unterstützt



 a| 
`sftp.log_nfiles`
 a| 
Nicht unterstützt



 a| 
`sftp.max_connections`
 a| 
Nicht unterstützt



 a| 
`sftp.max_connections_threshold`
 a| 
Nicht unterstützt



 a| 
`sftp.override_client_permissions`
 a| 
Nicht unterstützt



 a| 
`sis.max_vfiler_active_ops`
 a| 
Nicht unterstützt



 a| 
`snaplock.autocommit_period`
 a| 
Nicht unterstützt



 a| 
`snaplock.compliance.write_verify`
 a| 
Nicht unterstützt



 a| 
`snaplock.log.default_retention`
 a| 
Nicht unterstützt



 a| 
`snaplock.log.maximum_size`
 a| 
Nicht unterstützt



 a| 
`snapmirror.access`
 a| 
`*snapmirror create*`



 a| 
`snapmirror.checkip.enable`
 a| 
Nicht unterstützt



 a| 
`snapmirror.cmode.suspend`
 a| 
`*snapmirror quiesce*`



 a| 
`snapmirror.delayed_acks.enable`
 a| 
Nicht unterstützt



 a| 
`snapmirror.vsm.volread.smtape_enable`
 a| 
Nicht unterstützt



 a| 
`snapvalidator.version`
 a| 
Nicht unterstützt



 a| 
`snapvault.access`
 a| 
`*vserver peer*`



 a| 
`snapvault.enable`
 a| 
Nicht unterstützt



 a| 
`snapvault.lockvault_log_volume`
 a| 
Nicht unterstützt



 a| 
`snapvault.preservesnap`
 a| 
`snapmirror policy`



 a| 
`snapvault.snapshot_for_dr_backup`
 a| 
Nicht unterstützt



 a| 
`snmp.access`
 a| 
`*system services firewall policy modify -policy __policy_name__-service snmp -allow-list*`



 a| 
`snmp.enable`
 a| 
Nicht unterstützt



 a| 
`ssh.access`
 a| 
`*system services firewall policy modify -policy __policy_name_-service ssh -allow-list*`



 a| 
`ssh.enable`
 a| 
`*system services firewall policy modify -policy __policy_name__-service ssh -allow-list*`



 a| 
`ssh.idle.timeout`
 a| 
Nicht unterstützt



 a| 
`ssh.passwd_auth.enable`
 a| 
`*security login \{ show | create | delete \}-user-or-group-name _user_name_ -application ssh -authmethod publickey -role _role_name_ -vserver _vserver_name_*`



 a| 
`ssh.pubkey_auth.enable`
 a| 
`*security login modify -authmethod publickey*`



 a| 
`ssh1.enable`
 a| 
Nicht unterstützt



 a| 
`ssh2.enable`
 a| 
Nicht unterstützt



 a| 
ssl.Aktivieren
 a| 
`*security ssl modify -server -enabled*`



 a| 
`ssl.v2.enable`
 a| 
`*system services web modify -sslv2-enabled*`



 a| 
`ssl.v3.enable`
 a| 
`*system services web modify -sslv3-enabled*`



 a| 
`stats.archive.frequency_config`
 a| 
Nicht unterstützt

|===
[role="lead"]
*T*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`tape.reservations`
 a| 
`*options tape.reservations*`



 a| 
`telnet.access`
 a| 
`*system services firewall policy create -policy mgmt -service telnet -allow-list*`



 a| 
`telnet.distinct.enable`
 a| 
Nicht unterstützt



 a| 
`telnet.enable`
 a| 
`*system services firewall policy create -policy mgmt -service telnet -allow-list*`



 a| 
`tftpd.enable`
 a| 
Nicht unterstützt



 a| 
`tftpd.logging`
 a| 
Nicht unterstützt



 a| 
`tftpd.max_connections`
 a| 
Nicht unterstützt



 a| 
`tftpd.rootdir`
 a| 
Nicht unterstützt



 a| 
`timed.enable`
 a| 
`*system services ntp config modify -enabled*`



 a| 
`timed.log`
 a| 
Nicht unterstützt



 a| 
`timed.max_skew`
 a| 
Nicht unterstützt



 a| 
`timed.min_skew`
 a| 
Nicht unterstützt



 a| 
`timed.proto`
 a| 
Nicht unterstützt



 a| 
`timed.sched`
 a| 
Nicht unterstützt



 a| 
`timed.servers`
 a| 
`_cluster time-service ntp server_`



 a| 
`timed.window`
 a| 
Nicht unterstützt



 a| 
`trusted.hosts`
 a| 
Nicht unterstützt

|===
[role="lead"]
*V*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`vol.move.cutover.cpu.busy.limit`
 a| 
Nicht unterstützt



 a| 
`vol.move.cutover.disk.busy.limit`
 a| 
Nicht unterstützt



 a| 
`vsm.smtape.concurrent.cascade.support`
 a| 
Nicht unterstützt



 a| 
 a| 

|===
[role="lead"]
*W*

|===
| 7-Mode-Option | Befehl Clustered Data ONTAP 


 a| 
`wafl.default_nt_user`
 a| 
`*vserver nfs modify -default-win-user*`



 a| 
`wafl.default_unix_user`
 a| 
`*vserver cifs options modify -default-unix-user*`



 a| 
`wafl.inconsistent.asup_frequency.blks`
 a| 
`*system node run -node{_node_name_|local} options wafl.inconsistent.asup_frequency.blks*`



 a| 
`wafl.inconsistent.asup_frequency.time`
 a| 
`*system node run -node{_node_name_|local} options wafl.inconsistent.asup_frequency.time*`



 a| 
`wafl.inconsistent.ems_suppress`
 a| 
`*system node run -node{_node_name_|local} options wafl.inconsistent.ems_suppress*`



 a| 
`wafl.maxdirsize`
 a| 
`*vol create -maxdir-size*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`wafl.nt_admin_priv_map_to_root`
 a| 
`*vserver name-mapping create*`



 a| 
`wafl.root_only_chown`
 a| 
`*vserver nfs modify -chown-mode*`


NOTE: Verfügbar auf der erweiterten Berechtigungsebene



 a| 
`wafl.wcc_minutes_valid`
 a| 
Nicht unterstützt



 a| 
`webdav.enable`
 a| 
Nicht unterstützt

|===