---
permalink: copy-free/concept_considerations_for_local_users_and_groups_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, cifs, local, users, group 
summary: Bei der Migration von lokalen CIFS-Benutzern und -Gruppen müssen Sie jedoch unbedingt beachten, dass bei der Migration der Transition eine wichtige Voraussetzung ist. 
---
= Überlegungen für den Übergang von lokalen CIFS-Benutzern und -Gruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei der Migration von lokalen CIFS-Benutzern und -Gruppen müssen Sie jedoch unbedingt beachten, dass bei der Migration der Transition eine wichtige Voraussetzung ist.

* Umstellung von CIFS Datenservice-Volumes von einem 7-Mode Controller oder einer vFiler Einheit mit lokalen Benutzern und Gruppen auf eine SVM mit lokalen nicht-BUILTIN CIFS lokalen Benutzern und Gruppen wird nicht unterstützt.
+
Für den Übergang muss die SVM nur lokale BUILTIN CIFS Benutzer und Gruppen haben.

* Sie müssen sicherstellen, dass die Anzahl der lokalen Benutzer und Gruppen in 7-Mode nicht die lokale Benutzer und Gruppen-Grenze für ONTAP überschreitet.
+
Sie müssen sich an den technischen Support wenden, wenn die Anzahl der lokalen Benutzer und Gruppen in 7-Mode die in ONTAP definierte Obergrenze überschreitet.

* Ein lokales Benutzerkonto mit einem leeren Passwort oder lokalen Benutzerkonten mit Kennwörtern, die mehr als 14 Zeichen im 7-Mode-System enthalten, wird in die ONTAP-Software mit dem Passwort übertragen `*cifsUser@1*`.
+
Nach Abschluss der Umstellung können Sie über das Windows-System über das Kennwort auf diese Benutzer zugreifen `*cifsUser@1*`. Sie müssen dann das Passwort für diese lokalen CIFS-Benutzer auf der SVM mit dem folgenden Befehl manuell ändern:

+
`*cifs users-and-groups local-user set-password -vserver _svm_name_ -user-name _user_name_*`.

* Wenn die IP-Adresse des 7-Mode Transition Tools nicht über die Ziel-ONTAP-Software erreichbar ist, blockiert das 7-Mode Transition Tool den Übergang von lokalen CIFS-Benutzern und -Gruppen zur ONTAP-Software während der Vorprüfphase. Wenn dieser Fehler während der Vorprüfphase auftritt, verwenden Sie den
+
`*network ping -node local -destination _ip_address_*`

+
Befehl, um sicherzustellen, dass die IP-Adresse des 7-Mode Transition Tools über die Ziel-ONTAP-Software erreichbar ist. Sie können die bearbeiten `\etc\conf\transition-tool.conf` Datei, die mit dem 7-Mode Transition Tool installiert wird, um jede Konfigurationsoption, die vom Tool verwendet wird, zu ändern, z. B. die IP-Adresse des 7-Mode Transition Tools.

* Die SVM, zu der die lokalen Benutzer und Gruppen migriert werden, muss über eine Daten-LIF verfügen.
* Wenn eine lokale Gruppe mehrere Mitglieder-System-IDs (SIDs) einem einzelnen Domänenbenutzer oder einer Gruppe auf dem 7-Mode-System zugeordnet hat, blockiert das 7-Mode Transition Tool den Übergang von lokalen Benutzern und Gruppen zu ONTAP während der Vorprüfphase.
+
Wenn dieser Fehler während der Vorprüfphase auftritt, müssen Sie die zusätzlichen SIDs manuell entfernen, die einem einzelnen Domain-Benutzer oder einer einzelnen Gruppe auf dem 7-Mode-System zugeordnet sind. Anschließend müssen Sie die Vorabprüfung mit nur einem einzigen SID wiederholen, der dem Domänenbenutzer oder der Gruppe zugeordnet ist.

+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Troubleshooting_Workflow%3A_CIFS%3A_Device_attached_to_the_system_is_not_functioning["Fehlerbehebung Workflow: CIFS: Das an das System angeschlossene Gerät funktioniert nicht"]



*Verwandte Informationen*

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-cifs/home.html["SMB/CIFS-Management"]
