---
permalink: copy-free/concept_considerations_for_space_when_transitioning_san_volumes.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, space, considerations, san, volumes 
summary: Sie müssen sicherstellen, dass während des Übergangs ausreichend Speicherplatz in den Volumes verfügbar ist. Neben dem benötigten Platz zum Speichern von Daten und Snapshot Kopien benötigt der Umstiegsprozess auch 1 MB Speicherplatz pro LUN zur Aktualisierung bestimmter Dateisystem-Metadaten. 
---
= Überlegungen zu Speicherplatz beim Umstieg von SAN-Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen sicherstellen, dass während des Übergangs ausreichend Speicherplatz in den Volumes verfügbar ist. Neben dem benötigten Platz zum Speichern von Daten und Snapshot Kopien benötigt der Umstiegsprozess auch 1 MB Speicherplatz pro LUN zur Aktualisierung bestimmter Dateisystem-Metadaten.

Sie können das verwenden `df -h` Befehl auf dem 7-Mode Volume, um zu überprüfen, ob freier Speicherplatz von 1 MB pro LUN im Volume verfügbar ist. Das Volume sollte außerdem freien Speicherplatz aufweisen, der der Datenmenge entspricht, die voraussichtlich auf das Volume geschrieben werden soll, bevor die Hosts stillgelegt werden. Wenn das Volume nicht über genügend freien Speicherplatz verfügt, muss dem 7-Mode-Volume der erforderliche Speicherplatz hinzugefügt werden.

Wenn die Umstellung während der Importphase aufgrund eines fehlenden Speicherplatzes auf dem Volume fehlschlägt, wird die folgende EMS-Meldung erzeugt: `LUN.vol.proc.fail.no.space: Processing for LUNs in volume vol_name failed due to lack of space`.

Wenn es Volumes gibt, die Platz-reservierte LUNs enthalten, kann das Volumen um 1 MB pro LUN wachsen, sodass möglicherweise nicht ausreichend Speicherplatz zur Verfügung steht. In solchen Fällen muss der Speicherplatz, der hinzugefügt werden muss, die Größe der Snapshot-Reserve für das Volume sein. Nachdem dem Volume Speicherplatz hinzugefügt wurde, können Sie den verwenden `lun transition start` Befehl zum Umstellen der LUNs.

*Verwandte Informationen*

xref:task_recovering_from_a_failed_lun_transition.adoc[Wiederherstellung nach einer fehlerhaften LUN-Umstellung]

http://["NetApp Dokumentation: ONTAP 9"]
