---
permalink: copy-free/task_transitioning_to_clustered_ontap_8_3_from_a_7_mode_version_with_32_bit_data.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, prepare, 32, aggregates 
summary: 32-Bit-Aggregate, Volumes und Snapshot-Kopien werden in ONTAP 8.3 und höher nicht unterstützt. Daher müssen Sie die 32-Bit-Aggregate auf 64-Bit erweitern und vor der Umstellung alle 32-Bit-Volumes und Snapshot Kopien vom 7-Mode System finden und entfernen. 
---
= Vorbereitung auf den Wechsel von 7-Mode Systemen mit 32-Bit-Aggregaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
32-Bit-Aggregate, Volumes und Snapshot-Kopien werden in ONTAP 8.3 und höher nicht unterstützt. Daher müssen Sie die 32-Bit-Aggregate auf 64-Bit erweitern und vor der Umstellung alle 32-Bit-Volumes und Snapshot Kopien vom 7-Mode System finden und entfernen.

* *32-Bit Aggregate*
+
.. xref:task_expanding_an_aggregate_to_64_bit_format_without_adding_storage.adoc[Erweiterung eines Aggregats auf das 64-Bit-Format]
.. xref:task_finding_and_removing_32_bit_data_from_source_volumes_and_snapshot_copies.adoc[Suchen und Entfernen von 32-Bit Volumes und Snapshot Kopien]


* *32-bit Volumes oder Snapshot Kopien*
+
Selbst wenn Sie nur 64-Bit-Aggregate und -Volumen haben, könnten einige 32-Bit oder gemischte Format FlexVol Volumes oder Snapshot Kopien verbleiben. Vor dem Übergang müssen diese Volumes und Snapshot Kopien entfernt werden.

+
xref:task_finding_and_removing_32_bit_data_from_source_volumes_and_snapshot_copies.adoc[Suchen und Entfernen von 32-Bit Volumes und Snapshot Kopien]



*Verwandte Informationen*

https://www.netapp.com/pdf.html?item=/media/19679-tr-3978.pdf["Technischer Bericht 3978 von NetApp: In-Place-Erweiterung von 32-Bit-Aggregaten auf 64-Bit-Übersicht und Best Practices"^]
