---
permalink: copy-free/task_testing_workloads_and_applications.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, test, workload, application 
summary: Sie sollten alle Workloads und Applikationen manuell in der präproduktiven Umgebung testen. Anschließend können Sie die Produktion für eine kurze Dauer starten, um zu prüfen, ob ein Rollback erforderlich ist, bevor Sie das Projekt durchführen. 
---
= Testen der Workloads und Applikationen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten alle Workloads und Applikationen manuell in der präproduktiven Umgebung testen. Anschließend können Sie die Produktion für eine kurze Dauer starten, um zu prüfen, ob ein Rollback erforderlich ist, bevor Sie das Projekt durchführen.

Die ummigrierte Aggregate müssen mindestens 5 % freien physischen Speicherplatz aufweisen.


NOTE: Als Best Practice wird empfohlen, mindestens 20 % freien Speicherplatz in den übergewechselt.

Einige Vorgänge sind bei Vorproduktionstests eingeschränkt.

xref:concept_restrictions_during_preproduction_testing.adoc[Einschränkungen bei Vorproduktionstests]

.Schritte
. Client mit den übergewechselt Volumes verbinden.
. Falls Sie SAN-Workloads haben, führen Sie die Aufgaben zur Problemlösung des Hosts nach dem Umstieg auf den SAN-Hosts aus.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-7mtt-sanspl/home.html["San-Host-Umstellung und Problembehebung"]

. Testen aller Workloads und Applikationen, die die übermigrierte Daten und Konfiguration verwenden
. Überprüfen Sie im Dashboard des 7-Mode Transition Tool, ob den umgestiegen ist. Die Überwachung des freien physischen Speicherplatzes in den übersmigten Aggregaten erfolgt nicht mehr.
+
*Fehlerbehebung:* Wenn der Platz auf den überlauften Aggregaten erschöpft ist, können Sie Festplatten hinzufügen.

+
.. Melden Sie sich auf der erweiterten Berechtigungsebene an: +
`*set -privilege advanced*`
.. Wählen Sie die freien Festplatten aus den 7-Mode Platten-Shelves aus und fügen Sie Festplatten hinzu, um den Speicherplatz in den übergewechselt Aggregaten zu erhöhen: +
`*storage aggregate add-disks -aggregate _aggr_name_ -disklist _disk1_*`
+
Falls keine 7-Mode Spare-Festplatten verfügbar sind, können in den Cluster-Nodes Ersatzfestplatten aus den Festplatten-Shelfs verwendet werden. Dies erschwert jedoch den Rollback-Prozess.





Sie können damit beginnen, Produktionsdaten bereitzustellen.

[IMPORTANT]
====
Stellen Sie Daten in der Produktionsumgebung für einen kurzen Zeitraum bereit, um sicherzustellen, dass die Workloads in einer Produktionsumgebung korrekt funktionieren. Ein Rollback auf 7-Mode ist dabei nicht erforderlich. Sie dürfen diese Phase nicht verlängern und dürfen das Copy-Free Transition-Projekt aus den folgenden Gründen nicht verzögern:

* Die Wahrscheinlichkeit, dass in den übergewechselt werden kann, steigt, wenn neue Daten auf die Volumes geschrieben werden.
* Neue Daten, die während dieser Phase auf die Volumes geschrieben wurden, sind während des Rollbacks nicht verfügbar.


====
*Verwandte Informationen*

xref:concept_reverting_a_copy_free_transition_project.adoc[Durchführen eines Rollback auf 7-Mode]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9-Befehle"]
