---
permalink: copy-free/task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, prepare, cluster, snapmirror, relationship 
summary: Um 7-Mode Volume SnapMirror Beziehungen zu verschieben, müssen Sie die SnapMirror Lizenz dem Quell- und Ziel-Cluster hinzufügen. Es muss auch eine Cluster-Peer-Beziehung zwischen den Clustern erstellt werden, an die die primären und sekundären Volumes der SnapMirror Beziehungen migriert werden und die SnapMirror Zeitpläne erstellt werden. 
---
= Vorbereiten des Clusters für die Transition von Volume SnapMirror Beziehungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um 7-Mode Volume SnapMirror Beziehungen zu verschieben, müssen Sie die SnapMirror Lizenz dem Quell- und Ziel-Cluster hinzufügen. Es muss auch eine Cluster-Peer-Beziehung zwischen den Clustern erstellt werden, an die die primären und sekundären Volumes der SnapMirror Beziehungen migriert werden und die SnapMirror Zeitpläne erstellt werden.

Sie müssen die in definierten SnapMirror Zeitpläne in aufgezeichnet haben `/etc/snapmirror.conf` Datei des sekundären 7-Mode Systems.

.Schritte
. Fügen Sie die SnapMirror Lizenz sowohl auf dem Quell- als auch auf dem Ziel-Cluster hinzu:
+
`*system license add _license_code_*`

. Erstellen Sie von jedem Cluster die Cluster-Peer-Beziehung.
+
http://["Express-Konfiguration für Cluster und SVM-Peering"]

. Erstellen Sie Zeitpläne auf den sekundären SVMs, die den Zeitplänen im sekundären 7-Mode System entsprechen:
+
`*job schedule cron create*`



*Verwandte Informationen*

http://["ONTAP 9-Befehle"]
