---
permalink: snapmirror/concept_guidelines_for_transitioning_snaplock_volumes.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, guidelines, snaplock, volumes, requirements 
summary: Sie können 7-Mode SnapLock Volumes zu SnapLock Volumes überführen, die in ONTAP 9.5 oder früher erstellt wurden. Sie müssen die Anforderungen und Richtlinien für den Wechsel zu SnapLock Volumes kennen. 
---
= Richtlinien für die Transition von SnapLock Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um 7-Mode SnapLock Volumes auf ONTAP 9 zu übertragen, müssen Sie diese Anforderungen und Richtlinien kennen.

* Eine Transition von 7-Mode SnapLock Volumes wird nicht unterstützt, wenn die SnapLock Volumes LUNs enthalten.
* Sie können 7-Mode SnapLock Enterprise Volumes in jeder beliebigen ONTAP 9 Version zu SnapLock Enterprise Volumes übertragen, außer ONTAP 9.6.
* Sie können 7-Mode SnapLock Compliance Volumes in beliebigen ONTAP 9 Versionen, außer ONTAP 9.6, zu SnapLock Compliance Volumes übertragen.
* Beim Wechsel einer 7-Mode Volume SnapMirror Beziehung können Sie gestaffelte Transition (zuerst sekundärer und dann primärer Übergang) nur für SnapLock Enterprise Volumes nutzen.
+
Disaster Recovery (DR)-Beziehung zwischen 7-Mode primären Volumes und sekundären ONTAP Volumes wird nur für SnapLock Enterprise Volumes unterstützt, nicht aber für SnapLock Compliance Volumes.

+
xref:task_transitioning_a_data_protection_relationship.adoc[Umstellung einer SnapMirror-Beziehung auf einem Volume in einer gestaffelten Konfiguration^]

* Sie müssen eine 7-Mode Volume SnapMirror Beziehung zwischen SnapLock Compliance Volumes verschieben, indem Sie die primären und sekundären Volumes parallel verschieben.
+
xref:task_transitioning_a_volume_snapmirror_relationship_in_parallel.adoc[Paralleles Überführen einer Volume-SnapMirror-Beziehung^]

* Ab ONTAP 9.10.1 können im selben Aggregat SnapLock und nicht-SnapLock Volumes erstellt werden.
+
Um 7-Mode SnapLock Volumes zu ONTAP 9.10.1 oder höher zu übertragen, müssen Sie die ONTAP Volumes manuell mit dem erstellen `-snaplock-type {non-snaplock|compliance|enterprise}` Flagge. Nachdem Sie die Volumes manuell erstellt haben, managen Sie die Transition mit dem 7-Mode Transition Tool.

+
Wenn Sie mit dem 7-Mode Transition Tool ein Volume in ONTAP 9.10.1 oder höher erstellen, wird das Volume nicht als SnapLock Volume erstellt, was zu einer fehlgeschlagenen SnapMirror Basis führt.



*Verwandte Informationen*

https://["Archivierung und Compliance mit SnapLock Technologie"^]
