---
permalink: snapmirror/task_transitioning_a_stand_alone_volume.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, stand, alone, volume, snapmirror 
summary: Die Umstellung eines eigenständigen Volumes umfasst die Erstellung einer SnapMirror Beziehung, die Durchführung eines Basistransfers, die Durchführung inkrementeller Updates, das Monitoring des Vorgangs der Datenkopieerstellung, die SnapMirror Beziehung und das Verschieben des Client-Zugriffs vom 7-Mode Volume auf das Clustered Data ONTAP Volume. 
---
= Übergang eines eigenständigen Volumens
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Umstellung eines eigenständigen Volumes umfasst die Erstellung einer SnapMirror Beziehung, die Durchführung eines Basistransfers, die Durchführung inkrementeller Updates, das Monitoring des Vorgangs der Datenkopieerstellung, die SnapMirror Beziehung und das Verschieben des Client-Zugriffs vom 7-Mode Volume auf das Clustered Data ONTAP Volume.

* Das Cluster und die SVM müssen bereits eingerichtet sein.
* Sie müssen die Informationen zur Vorbereitung auf den Umstieg überprüft haben.
+
xref:task_preparing_for_transition.adoc[Die Vorbereitung auf den Umstieg ist möglich]



NetApp empfiehlt, das Ziel-ONTAP-Volume entsprechend den Attributen des 7-Mode Quell-Volume bereitzustellen. Zu den gleichen Attributen gehören u. a.:

* Volume-Größe: Das ONTAP Volume muss mindestens die Größe des 7-Mode Volumes aufweisen.
* Sprache: Die ONTAP-Lautstärkereinstellung sollte mit der Einstellung der 7-Mode-Lautstärke übereinstimmen.


Das 7-Mode Transition Tool stellt das ONTAP Volume automatisch mit Attributen bereit, die dem 7-Mode Volume entsprechen.

.Schritte
. Kopieren von Daten vom 7-Mode Volume auf das Clustered Data ONTAP Volume:
+
.. Falls Sie die Größe des TCP-Fensters für die SnapMirror Beziehung zwischen dem 7-Mode System und der SVM konfigurieren möchten, erstellen Sie eine Art SnapMirror-Richtlinie `async-mirror` Mit dem `window-size-for-tdp-mirror` Option.
+
Anschließend müssen Sie diese Richtlinie auf die TDP-SnapMirror-Beziehung zwischen dem 7-Mode System und der SVM anwenden.

+
Zur Verbesserung des SnapMirror Übertragungsdurchsatzes können Sie die TCP-Fenstergröße im Bereich von 256 KB bis 7 MB konfigurieren, sodass die Kopiervorgänge beim Umstieg schneller abgeschlossen werden. Der Standardwert für die TCP-Fenstergröße beträgt 2 MB.

+
[listing]
----
cluster1::> snapmirror policy create -vserver vs1 –policy tdp_policy -window-size-for-tdp-mirror 5MB -type async-mirror
----
.. Verwenden Sie die `snapmirror create` Befehl mit dem Beziehungstyp als TDP, um eine SnapMirror Beziehung zwischen dem 7-Mode System und der SVM zu erstellen.
+
Falls Sie eine SnapMirror-Richtlinie erstellt haben, um die TCP-Fenstergröße zu konfigurieren, müssen Sie die Richtlinie auf diese SnapMirror Beziehung anwenden.

+
[listing]
----
cluster1::> snapmirror create -source-path system7mode:dataVol20 -destination-path vs1:dst_vol -type TDP -policy tdp_policy
Operation succeeded: snapmirror create the relationship with destination vs1:dst_vol.
----
.. Verwenden Sie die `snapmirror initialize` Befehl zum Starten des Basistransfers.
+
[listing]
----
cluster1::> snapmirror initialize -destination-path vs1:dst_vol
Operation is queued: snapmirror initialize of destination vs1:dst_vol.
----
.. Verwenden Sie die `snapmirror show` Befehl zum Überwachen des Status.
+
[listing]
----
cluster1::>snapmirror show -destination-path vs1:dst_vol

                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           **Mirror State: Snapmirrored**
                    Relationship Status: Idle
                File Restore File Count: -
                 File Restore File List: -
                      Transfer Snapshot: -
                      Snapshot Progress: -
                         Total Progress: -
              Network Compression Ratio: -
                    Snapshot Checkpoint: -
                        Newest Snapshot: vs1(4080431166)_dst_vol.1
              Newest Snapshot Timestamp: 10/16 02:49:03
                      Exported Snapshot: vs1(4080431166)_dst_vol.1
            Exported Snapshot Timestamp: 10/16 02:49:03
                                Healthy: true
                       Unhealthy Reason: -
               Constituent Relationship: false
                Destination Volume Node: cluster1-01
                        Relationship ID: 97b205a1-54ff-11e4-9f30-005056a68289
                   Current Operation ID: -
                          Transfer Type: -
                         Transfer Error: -
                       Current Throttle: -
              Current Transfer Priority: -
                     Last Transfer Type: initialize
                    Last Transfer Error: -
                     Last Transfer Size: 152KB
Last Transfer Network Compression Ratio: 1:1
                 Last Transfer Duration: 0:0:6
                     Last Transfer From: system7mode:dataVol20
            Last Transfer End Timestamp: 10/16 02:43:53
                  Progress Last Updated: -
                Relationship Capability: 8.2 and above
                               Lag Time: -
           Number of Successful Updates: 0
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 155648
         Total Transfer Time in Seconds: 6
----
.. Je nachdem, ob Sie das Clustered Data ONTAP Volume manuell oder durch Einrichten eines SnapMirror Zeitplans aktualisieren möchten, führen Sie die entsprechende Aktion durch:
+
|===
| Ihr Ziel ist | Dann... 


 a| 
Aktualisieren Sie die Übertragungen manuell
 a| 
... Verwenden Sie die `snapmirror update` Befehl.
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
----
... Verwenden Sie die `snapmirror show` Befehl zum Überwachen des Status der Datenkopieerstellung
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----
... Fahren Sie mit Schritt 3 fort.




 a| 
Durchführung geplanter Updatetransfers
 a| 
... Verwenden Sie die `job schedule cron create` Befehl zum Erstellen eines Zeitplans für Aktualisierungsübertragungen.
+
[listing]
----
cluster1::> job schedule cron create -name 15_minute_sched -minute 15
----
... Verwenden Sie die `snapmirror modify` Befehl zum Anwenden des Zeitplans auf die SnapMirror Beziehung.
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule 15_minute_sched
----
... Verwenden Sie die `snapmirror show` Befehl zum Überwachen des Status der Datenkopieerstellung
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: 15_minute_sched
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----


|===


. Wenn Sie einen Zeitplan für inkrementelle Transfers haben, führen Sie die folgenden Schritte aus, wenn Sie die Umstellung durchführen können:
+
.. Verwenden Sie die `snapmirror quiesce` Befehl zum Deaktivieren aller zukünftigen Update-Transfers.
+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs1:dst_vol
----
.. Verwenden Sie die `snapmirror modify` Befehl zum Löschen des SnapMirror Zeitplans.
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule ""
----
.. Wenn Sie die SnapMirror Transfers früher stilllegen, verwenden Sie das `snapmirror resume` Befehl zum Aktivieren von SnapMirror Transfers.
+
[listing]
----
cluster1::> snapmirror resume -destination-path vs1:dst_vol
----


. Warten Sie, bis alle weiteren Transfers zwischen den 7-Mode Volumes und den Clustered Data ONTAP Volumes abgeschlossen sind, und trennen Sie dann den Client-Zugriff von den 7-Mode Volumes, um mit der Umstellung zu beginnen.
. Verwenden Sie die `snapmirror update` Befehl zum Durchführen einer letzten Datenaktualisierung für das Clustered Data ONTAP Volume.
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
Operation is queued: snapmirror update of destination vs1:dst_vol.
----
. Verwenden Sie die `snapmirror show` Befehl zur Überprüfung, ob der letzte Transfer erfolgreich war.
. Verwenden Sie die `snapmirror break` Befehl zum Abbrechen der SnapMirror Beziehung zwischen dem 7-Mode Volume und dem Clustered Data ONTAP Volume.
+
[listing]
----
cluster1::> snapmirror break -destination-path vs1:dst_vol
[Job 60] Job succeeded: SnapMirror Break Succeeded
----
. Wenn LUNs auf den Volumes auf der erweiterten Berechtigungsebene konfiguriert sind, verwenden Sie das `lun transition 7-mode show` Befehl, um zu überprüfen, ob die LUNs migriert wurden.
+
Sie können auch die verwenden `lun show` Befehl für das Clustered Data ONTAP Volume, um alle LUNs anzuzeigen, die erfolgreich migriert wurden.

. Verwenden Sie die `snapmirror delete` Befehl zum Löschen der SnapMirror Beziehung zwischen dem 7-Mode Volume und dem Clustered Data ONTAP Volume
+
[listing]
----
cluster1::> snapmirror delete -destination-path vs1:dst_vol
----
. Verwenden Sie die `snapmirror release` Befehl zum Entfernen der SnapMirror Beziehungsinformationen aus dem 7-Mode System.
+
[listing]
----
system7mode> snapmirror release dataVol20 vs1:dst_vol
----


Sie müssen die SVM-Peer-Beziehung zwischen dem 7-Mode System und der SVM löschen, wenn alle erforderlichen Volumes des 7-Mode Systems auf die SVM verschoben werden.

*Verwandte Informationen*

xref:task_resuming_a_failed_snapmirror_transfer_transition.adoc[Wiederaufnahme eines fehlgeschlagenen SnapMirror Basistransfers]

xref:task_recovering_from_a_failed_lun_transition.adoc[Wiederherstellung nach einer fehlerhaften LUN-Umstellung]

xref:task_configuring_a_tcp_window_size_for_snapmirror_relationships.adoc[Konfigurieren einer TCP-Fenstergröße für SnapMirror Beziehungen]
